#!/usr/bin/env bash
# Generated by https://github.com/flowgent-labs/mcpfather
set -euo pipefail

# ============================================================
# MCP Server Client Script
# Quick test helper for the generated MCP server.
#
# Usage:
#   ./mcpclient.sh                  Show this help message
#   ./mcpclient.sh help             Show this help message
#   ./mcpclient.sh list-tools       List all available tools
#   ./mcpclient.sh call <tool> [--key value ...] [--body '<json>']
#
# Environment variables:
#   MCP_UPSTREAM_TOKEN    - Bearer token for MCP server auth
#   MCP_SERVER_ENDPOINT        - Server URL (default: http://localhost:8080/mcp)
#   MCP_SERVER_DOWNLOAD_DIR      - Directory for download responses (default: ./download)
# ============================================================

SERVER_URL="${MCP_SERVER_ENDPOINT:-http://localhost:8080/mcp}"
SESSION_ID=""
DOWNLOAD_DIR="${MCP_SERVER_DOWNLOAD_DIR:-download}"

usage() {
  cat <<'USAGE'
mcpclient.sh — MCP Server Client Script

Usage:
  ./mcpclient.sh [command] [arguments]

Commands:
  (no args)           Show this help message
  help                Show this help message
  list-tools          List all available tools
  call <tool> [--key value ...] [--body '<json>']  Call a tool

  --key value         Tool argument (query/path parameter)
  --body '<json>'     JSON request body sent as application/json to upstream
                      (only upload tools accept @file:///, @https://,
                      or @http:// file references in their file args)
  --file <path>       Shortcut: sets the file arg to @file:///<path>
                      (equivalent to --file @file:///<path>)

Environment:
  MCP_SERVER_ENDPOINT        Override server URL (default: http://localhost:8080/mcp)
  MCP_UPSTREAM_TOKEN    Bearer token for server auth
  MCP_SERVER_DOWNLOAD_DIR      Directory for file download (default: ./download)

Tips:
  - Always uses --noproxy '*' to avoid proxy issues with localhost
  - If the server is running on a different port:
      MCP_SERVER_ENDPOINT=http://localhost:9090/mcp ./mcpclient.sh
  - If authentication is required:
      MCP_UPSTREAM_TOKEN=your-token ./mcpclient.sh call <tool>
  - Download tools auto-save to $DOWNLOAD_DIR
  - The script auto-initializes a session on first call

Examples:
  # Call a tool with query/path arguments
  ./mcpclient.sh call getProject --projectKey myproject
  # Call a tool with a file upload
  ./mcpclient.sh call UploadFile --file /tmp/report.pdf
  # Call a tool with remote file + body
  ./mcpclient.sh call uploadScanReport --scanId 12345 --file /tmp/report.pdf
  # The server receives file=@file:///tmp/report.pdf (file-ref upload)
USAGE
  cat <<'EOEX'
  # CreateBlobstoresFile (POST)
  ./mcpclient.sh call CreateBlobstoresFile '{"body": {"name": "name_value", "path": "path_value", "softQuota": {}, "softQuotaAttributes": {}}}'
EOEX
  cat <<'EOEX'
  # CreateBlobstoresS3 (POST)
  ./mcpclient.sh call CreateBlobstoresS3 '{"body": {"bucketConfiguration": {}, "name": "s3", "softQuota": {}, "type": "S3"}}'
EOEX
  cat <<'EOEX'
  # CreateCleanupRun (POST)
  ./mcpclient.sh call CreateCleanupRun '{"body": {"dryRun": false, "policy": "policy_value", "repository": "repository_value"}}'
EOEX
  cat <<'EOEX'
  # CreateComponents (POST)
  ./mcpclient.sh call CreateComponents '{"repository": "repository_value"}'
EOEX
  cat <<'EOEX'
  # CreateConfigurationAssetsImport (POST)
  ./mcpclient.sh call CreateConfigurationAssetsImport '{"X-Nexus-Migration-Protocol-Version": "X-Nexus-Migration-Protocol-Version_value", "repositoryName": "repositoryName_value"}'
EOEX
  cat <<'EOEX'
  # CreateConfigurationCipher (POST)
  ./mcpclient.sh call CreateConfigurationCipher '{"X-Nexus-Migration-Protocol-Version": "X-Nexus-Migration-Protocol-Version_value", "body": "value"}'
EOEX
  cat <<'EOEX'
  # CreateConfigurationTransferComplete (POST)
  ./mcpclient.sh call CreateConfigurationTransferComplete '{"X-Nexus-Migration-Protocol-Version": "X-Nexus-Migration-Protocol-Version_value", "body": {"failedAssetTransferCount": 0, "message": "message_value", "repositoryName": "repositoryName_value", "skippedAssetTransferCount": 0, "successful": false, "successfulAssetTransferCount": 0, "timestamp": 0}}'
EOEX
  cat <<'EOEX'
  # CreateEmailVerify (POST)
  ./mcpclient.sh call CreateEmailVerify '{"body": "value"}'
EOEX
  cat <<'EOEX'
  # CreateInternalCleanupPolicies (POST)
  ./mcpclient.sh call CreateInternalCleanupPolicies '{"body": {"criteriaAssetRegex": "criteriaAssetRegex_value", "criteriaLastBlobUpdated": 0, "criteriaLastDownloaded": 0, "criteriaReleaseType": "RELEASES", "format": "format_value", "inUseCount": 0, "name": "name_value", "notes": "notes_value", "repositories": [], "retain": 0, "sortBy": "sortBy_value"}}'
EOEX
  cat <<'EOEX'
  # CreateInternalUiSecurityAccessCheck (POST)
  ./mcpclient.sh call CreateInternalUiSecurityAccessCheck '{"body": {"endpoint": "/service/rest/v1/repositories", "method": "GET", "roleId": "nx-admin", "userId": "john.doe"}}'
EOEX
  cat <<'EOEX'
  # CreatePlan (POST)
  ./mcpclient.sh call CreatePlan '{"blobStores": [], "endDate": "endDate_value", "repositories": [], "sinceDays": 0, "sinceHours": 0, "sinceMinutes": 30, "startDate": "startDate_value"}'
EOEX
  cat <<'EOEX'
  # CreateRecoveryMode (POST)
  ./mcpclient.sh call CreateRecoveryMode '{}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAlpineGroup (POST)
  ./mcpclient.sh call CreateRepositoriesAlpineGroup '{"body": {"alpineSigning": {}, "group": {}, "name": "internal", "online": true, "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAlpineHosted (POST)
  ./mcpclient.sh call CreateRepositoriesAlpineHosted '{"body": {"alpineSigning": {}, "cleanup": {}, "component": {}, "name": "internal", "online": true, "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAlpineProxy (POST)
  ./mcpclient.sh call CreateRepositoriesAlpineProxy '{"body": {"alpineSigning": {}, "cleanup": {}, "firewall": {}, "httpClient": {}, "name": "internal", "negativeCache": {}, "online": true, "proxy": {}, "replication": {}, "routingRuleName": "routingRuleName_value", "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAnsiblegalaxyGroup (POST)
  ./mcpclient.sh call CreateRepositoriesAnsiblegalaxyGroup '{"body": {"group": {}, "name": "internal", "online": true, "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAptHosted (POST)
  ./mcpclient.sh call CreateRepositoriesAptHosted '{"body": {"apt": {}, "aptSigning": {}, "cleanup": {}, "component": {}, "name": "internal", "online": true, "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesAptProxy (POST)
  ./mcpclient.sh call CreateRepositoriesAptProxy '{"body": {"apt": {}, "aptSigning": {}, "cleanup": {}, "firewall": {}, "httpClient": {}, "name": "internal", "negativeCache": {}, "online": true, "proxy": {}, "replication": {}, "routingRuleName": "routingRuleName_value", "storage": {}}}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesHealthCheck (POST)
  ./mcpclient.sh call CreateRepositoriesHealthCheck '{"repositoryName": "repositoryName_value", "source": "source_value"}'
EOEX
  cat <<'EOEX'
  # CreateRepositoriesInvalidateCache (POST)
  ./mcpclient.sh call CreateRepositoriesInvalidateCache '{"repositoryName": "repositoryName_value"}'
EOEX
}

# --- Auth helper ---

get_auth_header() {
  if [ -n "${MCP_UPSTREAM_TOKEN:-}" ]; then
    printf '%s' "Authorization: Bearer ${MCP_UPSTREAM_TOKEN}"
  fi
}

# --- Session helpers ---

init_session() {
  echo "[*] Initializing MCP session at $SERVER_URL ..." >&2
  local headers_file
  headers_file=$(mktemp)

  local curl_args=(
    -s -D "$headers_file"
    --noproxy '*'
    -X POST "$SERVER_URL"
    -H "Content-Type: application/json"
    -d '{"jsonrpc":"2.0","id":0,"method":"initialize","params":{"protocolVersion":"2024-11-05","capabilities":{},"clientInfo":{"name":"client","version":"1.0"}}}'
  )

  local auth_header
  auth_header=$(get_auth_header)
  if [ -n "$auth_header" ]; then
    curl_args+=(-H "$auth_header")
  fi

  local body
  body=$(curl "${curl_args[@]}")

  SESSION_ID=$(grep -oi "Mcp-Session-Id: [^ ]*" "$headers_file" | head -1 | awk '{print $2}' | tr -d '"\r' || true)
  rm -f "$headers_file"
  if [ -z "$SESSION_ID" ]; then
    echo "[!] Failed to get session ID. Is the server running?" >&2
    echo "[!] Response: $body" >&2
    return 1
  fi
  echo "[+] Session: $SESSION_ID" >&2
}

# --- MCP JSON-RPC helpers ---

mcp_request() {
  local method="$1"
  local id="${2:-1}"
  local params
  if [ $# -ge 3 ]; then params="$3"; else params='{ }'; fi

  if [ -z "$SESSION_ID" ]; then
    init_session
  fi

  local curl_args=(
    -s --noproxy '*'
    -X POST "$SERVER_URL"
    -H "Content-Type: application/json"
    -H "Mcp-Session-Id: $SESSION_ID"
    -d "{\"jsonrpc\":\"2.0\",\"id\":$id,\"method\":\"$method\",\"params\":$params}"
  )

  local auth_header
  auth_header=$(get_auth_header)
  if [ -n "$auth_header" ]; then
    curl_args+=(-H "$auth_header")
  fi

  curl "${curl_args[@]}"
}

# --- Tool helpers ---

list_tools() {
  echo "[*] Listing tools ..." >&2
  local result
  result=$(mcp_request tools/list 1)
  if command -v python3 >/dev/null 2>&1; then
    echo "$result" | python3 -c '
import json, sys
try:
    data = json.load(sys.stdin)
    tools = data.get("result", {}).get("tools", [])
    maxlen = max((len(t["name"]) for t in tools), default=0)
    for t in tools:
        desc = t.get("description", "")
        if desc:
            # take first line only
            desc = desc.split("\n")[0].strip()
        name = t["name"]
        print(f"  {name:<{maxlen+4}}{desc}")
except Exception as e:
    print("(parse error: {})".format(e), file=sys.stderr)
'
  else
    # Fallback: print raw result
    echo "$result"
  fi
}

call_tool() {
  local tool_name="${1:?Usage: call_tool <tool-name> [--key value ...] [--body '<json>']}"
  shift
  local args='{}'
  local file_path=""
  local body_json=""

  # Detect argument style: --key value pairs (new) vs positional JSON (legacy).
  if [ $# -gt 0 ] && [ "${1#--}" != "$1" ]; then
    # New style: --key value [--key value ...] [--body '<json>'] [--file <path>]
    while [ $# -gt 0 ]; do
      case "$1" in
        --file=*)
          file_path="${1#--file=}"
          shift
          ;;
        --file)
          file_path="${2:?--file requires a path argument}"
          shift 2
          ;;
        --body=*)
          body_json="${1#--body=}"
          shift
          ;;
        --body)
          body_json="${2:?--body requires a JSON value}"
          shift 2
          ;;
        --*)
          local key="${1#--}"
          local value
          if [[ "$key" == *"="* ]]; then
            # Support --key=value syntax
            value="${key#*=}"
            key="${key%%=*}"
            shift
          else
            value="${2:?$1 requires a value}"
            shift 2
          fi
          if command -v python3 >/dev/null 2>&1; then
            # Parse value: try JSON first, fall back to string.
            args=$(python3 -c "
import json, sys
v = '''$value'''
# Try JSON parse; if it fails treat as raw string.
try:    v = json.loads(v)
except: pass
args = json.loads('''$args''')
args['$key'] = v
print(json.dumps(args))
" 2>/dev/null || echo "$args")
          else
            # Minimal fallback: always treat as string.
            args=$(echo "$args" | sed 's/}$//')
            args="${args},\"$key\":\"$value\"}"
          fi
          ;;
        *)
          shift
          ;;
      esac
    done

    # If --file is provided, auto-prefix @file:// and set as the "file" arg.
    if [ -n "$file_path" ]; then
      if [ ! -f "$file_path" ]; then
        echo "[!] File not found: $file_path" >&2
        return 1
      fi
      local abs_path
      abs_path=$(realpath "$file_path" 2>/dev/null || echo "$file_path")
      local file_size
      file_size=$(wc -c < "$file_path" | tr -d ' ')
      echo "[*] Uploading file via ref: @file://$abs_path ($file_size bytes)" >&2
      if command -v python3 >/dev/null 2>&1; then
        args=$(python3 -c "
import json
args = json.loads('''$args''')
args['file'] = '@file://$abs_path'
print(json.dumps(args))
" 2>/dev/null || echo "$args")
      fi
    fi

    # Merge --body into args.
    if [ -n "$body_json" ]; then
      if command -v python3 >/dev/null 2>&1; then
        args=$(python3 -c "
import json
args = json.loads('''$args''')
args['body'] = json.loads('''$body_json''')
print(json.dumps(args))
" 2>/dev/null || echo "$args")
      fi
    fi
  else
    # Legacy style: positional JSON arg with optional --file.
    while [ $# -gt 0 ]; do
      case "$1" in
        --file)
          file_path="${2:?--file requires a path argument}"
          shift 2
          ;;
        *)
          args="$1"
          shift
          ;;
      esac
    done

    # If --file is provided, set as file ref URI arg.
    if [ -n "$file_path" ]; then
      if [ ! -f "$file_path" ]; then
        echo "[!] File not found: $file_path" >&2
        return 1
      fi
      local abs_path
      abs_path=$(realpath "$file_path" 2>/dev/null || echo "$file_path")
      local file_size
      file_size=$(wc -c < "$file_path" | tr -d ' ')
      echo "[*] Uploading file via ref: @file://$abs_path ($file_size bytes)" >&2
      if command -v python3 >/dev/null 2>&1; then
        args=$(python3 -c "
import json
args = json.loads('$args')
args['file'] = '@file://$abs_path'
print(json.dumps(args))
" 2>/dev/null || echo "$args")
      fi
    fi
  fi

  echo "[*] Calling tool: $tool_name" >&2
  echo "[*] Args: $args" >&2

  local result
  result=$(mcp_request tools/call 1 "{\"name\":\"$tool_name\",\"arguments\":$args}")

  # Check for error
  if echo "$result" | grep -q '"isError":true'; then
    echo "[!] Tool returned an error:" >&2
    echo "$result" | python3 -m json.tool 2>/dev/null || echo "$result"
    return 1
  fi

  # Pretty print JSON response
  echo "$result" | python3 -m json.tool 2>/dev/null || echo "$result"
}

# --- Main ---

case "${1:-help}" in
  help|--help|-h)
    usage
    ;;
  list-tools|list)
    init_session
    list_tools
    ;;
  call)
    shift
    init_session
    call_tool "$@"
    ;;
  *)
    init_session
    call_tool "$@"
    ;;
esac
