// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateRepositoriesRebuildIndex tool
const CreateRepositoriesRebuildIndexInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to rebuild index\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateRepositoriesRebuildIndexMCPTool creates the MCP Tool instance for CreateRepositoriesRebuildIndex
func NewCreateRepositoriesRebuildIndexMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateRepositoriesRebuildIndex",
		"Schedule a 'Repair - Rebuild repository search' Task. Hosted or proxy repositories only.",
		[]byte(CreateRepositoriesRebuildIndexInputSchema),
	)
}

// CreateRepositoriesRebuildIndexHandler is the handler function for the CreateRepositoriesRebuildIndex tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateRepositoriesRebuildIndexHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/repositories/{repositoryName}/rebuild-index", args, []string{"repositoryName"}, contentType, "CreateRepositoriesRebuildIndex")
}
