// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateComponents tool
const CreateComponentsInputSchema = "{\n  \"properties\": {\n    \"repository\": {\n      \"description\": \"Name of the repository to which you would like to upload the component\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repository\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateComponentsMCPTool creates the MCP Tool instance for CreateComponents
func NewCreateComponentsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateComponents",
		"Upload a single component",
		[]byte(CreateComponentsInputSchema),
	)
}

// CreateComponentsHandler is the handler function for the CreateComponents tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateComponentsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/components", args, []string{}, contentType, "CreateComponents")
}
