// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateInternalUiSecurityAccessCheck tool
const CreateInternalUiSecurityAccessCheckInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"Access check request\",\n      \"properties\": {\n        \"endpoint\": {\n          \"description\": \"The API endpoint to check access for.\",\n          \"example\": \"/service/rest/v1/repositories\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"method\": {\n          \"description\": \"The HTTP method for the endpoint.\",\n          \"example\": \"GET\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"roleId\": {\n          \"description\": \"The role ID to check access for. Mutually exclusive with userId.\",\n          \"example\": \"nx-admin\",\n          \"pattern\": \"^[a-zA-Z0-9._-]{1,200}$\",\n          \"type\": \"string\"\n        },\n        \"userId\": {\n          \"description\": \"The user ID to check access for. If omitted, checks access for the current user.\",\n          \"example\": \"john.doe\",\n          \"pattern\": \"^[a-zA-Z0-9._-]{1,200}$\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"endpoint\",\n        \"method\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateInternalUiSecurityAccessCheck tool (Status: 200, Content-Type: application/json)
const CreateInternalUiSecurityAccessCheckResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Access check result\n\n## Response Structure\n\n- Structure (Type: object):\n  - **chains**: The permission chains showing how access is granted (user -> role -> privilege -> permission) (Type: array):\n    - **Items**: The permission chains showing how access is granted (user -> role -> privilege -> permission) (Type: object):\n      - **permission**: The permission string (Type: string):\n      - **privilege**: The privilege in the permission chain (Type: object):\n        - **id**: The entity ID (Type: string):\n        - **name**: The entity display name (Type: string):\n      - **[cyclic reference]**\n      - **[cyclic reference]**\n  - **hasAccess**: Whether the user/role has access to the endpoint (Type: boolean):\n  - **relatedEndpoints**: Related API endpoints that use similar permissions (Type: array):\n    - **Items**: Related API endpoints that use similar permissions (Type: object):\n      - **description**: Description of the endpoint (Type: string):\n      - **endpoint**: The API endpoint path (Type: string):\n      - **method**: The HTTP method (Type: string):\n      - **permission**: The permission required for this endpoint (Type: string):\n  - **requiredPermission**: The permission required to access the endpoint (Type: string):\n"

// NewCreateInternalUiSecurityAccessCheckMCPTool creates the MCP Tool instance for CreateInternalUiSecurityAccessCheck
func NewCreateInternalUiSecurityAccessCheckMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateInternalUiSecurityAccessCheck",
		"Check if a user or role has access to an API endpoint",
		[]byte(CreateInternalUiSecurityAccessCheckInputSchema),
	)
}

// CreateInternalUiSecurityAccessCheckHandler is the handler function for the CreateInternalUiSecurityAccessCheck tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateInternalUiSecurityAccessCheckHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/internal/ui/security/access-check", args, []string{}, contentType, "CreateInternalUiSecurityAccessCheck")
}
