// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityAtlassianCrowdClearCache tool
const CreateSecurityAtlassianCrowdClearCacheInputSchema = "{\n  \"type\": \"object\"\n}"

// NewCreateSecurityAtlassianCrowdClearCacheMCPTool creates the MCP Tool instance for CreateSecurityAtlassianCrowdClearCache
func NewCreateSecurityAtlassianCrowdClearCacheMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityAtlassianCrowdClearCache",
		"Clear Atlassian Crowd cache",
		[]byte(CreateSecurityAtlassianCrowdClearCacheInputSchema),
	)
}

// CreateSecurityAtlassianCrowdClearCacheHandler is the handler function for the CreateSecurityAtlassianCrowdClearCache tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityAtlassianCrowdClearCacheHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/atlassian-crowd/clear-cache", args, []string{}, contentType, "CreateSecurityAtlassianCrowdClearCache")
}
