// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
	"strings"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSystemLicense tool
const CreateSystemLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the CreateSystemLicense tool (Status: 0, Content-Type: application/json)
const CreateSystemLicenseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: object):\n  - **contactCompany** (Type: string):\n  - **contactEmail** (Type: string):\n  - **contactName** (Type: string):\n  - **effectiveDate** (Type: string, date-time):\n  - **expirationDate** (Type: string, date-time):\n  - **features** (Type: string):\n  - **fingerprint** (Type: string):\n  - **licenseType** (Type: string):\n  - **licensedUsers** (Type: string):\n  - **maxRepoComponents** (Type: integer, int64):\n  - **maxRepoRequests** (Type: integer, int64):\n"

// NewCreateSystemLicenseMCPTool creates the MCP Tool instance for CreateSystemLicense
func NewCreateSystemLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSystemLicense",
		"Upload a new license file. - Server must be restarted to take effect",
		[]byte(CreateSystemLicenseInputSchema),
	)
}

// CreateSystemLicenseHandler is the handler function for the CreateSystemLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSystemLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	// FileRef: collect file URI values. Optional files that are not provided
	// are omitted from the multipart body. Non-URI values remain available for
	// anyOf binary|string multipart schemas and are forwarded as text fields.
	fileRefs := map[string]string{
		"file": "",
	}
	if uri, ok := args["file"].(string); ok {
		// Strip @ prefix (AI agent convention: @file://, @https://, @http://).
		// The client MUST provide an explicit scheme (file://, https://, http://).
		// Bare paths are treated as literal values, NOT auto-prefixed to file://,
		// because a bare path may be a legitimate non-file string argument.
		uri = strings.TrimPrefix(uri, "@")
		fileRefs["file"] = uri
	}
	return mcputils.ForwardBinaryUploadRequest(ctx, upstream, "POST", "/service/rest/v1/system/license", args, fileRefs, "application/octet-stream", "CreateSystemLicense")
}
