// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateRepositoriesInvalidateCache tool
const CreateRepositoriesInvalidateCacheInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to invalidate cache\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateRepositoriesInvalidateCacheMCPTool creates the MCP Tool instance for CreateRepositoriesInvalidateCache
func NewCreateRepositoriesInvalidateCacheMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateRepositoriesInvalidateCache",
		"Invalidate repository cache. Proxy or group repositories only.",
		[]byte(CreateRepositoriesInvalidateCacheInputSchema),
	)
}

// CreateRepositoriesInvalidateCacheHandler is the handler function for the CreateRepositoriesInvalidateCache tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateRepositoriesInvalidateCacheHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/repositories/{repositoryName}/invalidate-cache", args, []string{"repositoryName"}, contentType, "CreateRepositoriesInvalidateCache")
}
