// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateScriptRun tool
const CreateScriptRunInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"oneOf\": [\n        {\n          \"title\": \"Schema for application/json\",\n          \"type\": \"string\"\n        },\n        {\n          \"title\": \"Schema for text/plain\",\n          \"type\": \"string\"\n        }\n      ]\n    },\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateScriptRunMCPTool creates the MCP Tool instance for CreateScriptRun
func NewCreateScriptRunMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateScriptRun",
		"Run stored script by name",
		[]byte(CreateScriptRunInputSchema),
	)
}

// CreateScriptRunHandler is the handler function for the CreateScriptRun tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateScriptRunHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/script/{name}/run", args, []string{"name"}, contentType, "CreateScriptRun")
}
