// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityRoles tool
const CreateSecurityRolesInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"A role configuration\",\n      \"properties\": {\n        \"description\": {\n          \"description\": \"The description of this role.\",\n          \"type\": \"string\"\n        },\n        \"id\": {\n          \"description\": \"The id of the role.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the role.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"privileges\": {\n          \"description\": \"The list of privileges assigned to this role.\",\n          \"items\": {\n            \"description\": \"The list of privileges assigned to this role.\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        },\n        \"roles\": {\n          \"description\": \"The list of roles assigned to this role.\",\n          \"items\": {\n            \"description\": \"The list of roles assigned to this role.\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        }\n      },\n      \"required\": [\n        \"id\",\n        \"name\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityRolesMCPTool creates the MCP Tool instance for CreateSecurityRoles
func NewCreateSecurityRolesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityRoles",
		"Create role",
		[]byte(CreateSecurityRolesInputSchema),
	)
}

// CreateSecurityRolesHandler is the handler function for the CreateSecurityRoles tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityRolesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/roles", args, []string{}, contentType, "CreateSecurityRoles")
}
