// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSystemEula tool
const CreateSystemEulaInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"accepted\": {\n          \"type\": \"boolean\"\n        },\n        \"disclaimer\": {\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewCreateSystemEulaMCPTool creates the MCP Tool instance for CreateSystemEula
func NewCreateSystemEulaMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSystemEula",
		"Set the Community Eula status.",
		[]byte(CreateSystemEulaInputSchema),
	)
}

// CreateSystemEulaHandler is the handler function for the CreateSystemEula tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSystemEulaHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/system/eula", args, []string{}, contentType, "CreateSystemEula")
}
