// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityPrivilegesWildcard tool
const CreateSecurityPrivilegesWildcardInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The privilege to create.\",\n      \"properties\": {\n        \"description\": {\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the privilege.  This value cannot be changed.\",\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"pattern\": {\n          \"description\": \"A colon separated list of parts that create a permission string.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"name\",\n        \"pattern\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityPrivilegesWildcardMCPTool creates the MCP Tool instance for CreateSecurityPrivilegesWildcard
func NewCreateSecurityPrivilegesWildcardMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityPrivilegesWildcard",
		"Create a wildcard type privilege.",
		[]byte(CreateSecurityPrivilegesWildcardInputSchema),
	)
}

// CreateSecurityPrivilegesWildcardHandler is the handler function for the CreateSecurityPrivilegesWildcard tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityPrivilegesWildcardHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/privileges/wildcard", args, []string{}, contentType, "CreateSecurityPrivilegesWildcard")
}
