// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateTasksStop tool
const CreateTasksStopInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the task to stop\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateTasksStopMCPTool creates the MCP Tool instance for CreateTasksStop
func NewCreateTasksStopMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateTasksStop",
		"Stop task",
		[]byte(CreateTasksStopInputSchema),
	)
}

// CreateTasksStopHandler is the handler function for the CreateTasksStop tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateTasksStopHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/tasks/{id}/stop", args, []string{"id"}, contentType, "CreateTasksStop")
}
