// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityContentSelectors tool
const CreateSecurityContentSelectorsInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"description\": {\n          \"description\": \"A human-readable description\",\n          \"type\": \"string\"\n        },\n        \"expression\": {\n          \"description\": \"The expression used to identify content\",\n          \"example\": \"format == \\\"maven2\\\" and path =^ \\\"/org/sonatype/nexus\\\"\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The content selector name cannot be changed after creation\",\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"expression\",\n        \"name\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewCreateSecurityContentSelectorsMCPTool creates the MCP Tool instance for CreateSecurityContentSelectors
func NewCreateSecurityContentSelectorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityContentSelectors",
		"Create a new content selector",
		[]byte(CreateSecurityContentSelectorsInputSchema),
	)
}

// CreateSecurityContentSelectorsHandler is the handler function for the CreateSecurityContentSelectors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityContentSelectorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/content-selectors", args, []string{}, contentType, "CreateSecurityContentSelectors")
}
