// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityPrivilegesApplication tool
const CreateSecurityPrivilegesApplicationInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The privilege to create.\",\n      \"properties\": {\n        \"actions\": {\n          \"description\": \"A collection of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.\",\n          \"items\": {\n            \"description\": \"A collection of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.\",\n            \"enum\": [\n              \"READ\",\n              \"BROWSE\",\n              \"EDIT\",\n              \"ADD\",\n              \"DELETE\",\n              \"RUN\",\n              \"START\",\n              \"STOP\",\n              \"ASSOCIATE\",\n              \"DISASSOCIATE\",\n              \"ALL\"\n            ],\n            \"type\": \"string\"\n          },\n          \"minItems\": 1,\n          \"type\": \"array\"\n        },\n        \"description\": {\n          \"type\": \"string\"\n        },\n        \"domain\": {\n          \"description\": \"The domain (i.e. 'blobstores', 'capabilities' or even '*' for all) that this privilege is granting access to.  Note that creating new privileges with a domain is only necessary when using plugins that define their own domain(s).\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the privilege.  This value cannot be changed.\",\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"actions\",\n        \"domain\",\n        \"name\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityPrivilegesApplicationMCPTool creates the MCP Tool instance for CreateSecurityPrivilegesApplication
func NewCreateSecurityPrivilegesApplicationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityPrivilegesApplication",
		"Create an application type privilege.",
		[]byte(CreateSecurityPrivilegesApplicationInputSchema),
	)
}

// CreateSecurityPrivilegesApplicationHandler is the handler function for the CreateSecurityPrivilegesApplication tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityPrivilegesApplicationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/privileges/application", args, []string{}, contentType, "CreateSecurityPrivilegesApplication")
}
