// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateConfigurationCipher tool
const CreateConfigurationCipherInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    },\n    \"body\": {\n      \"description\": \"Cipher password as plain text\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\",\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateConfigurationCipher tool (Status: 200, Content-Type: application/json)
const CreateConfigurationCipherResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Cipher password set successfully\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationCipher tool (Status: 400, Content-Type: application/json)
const CreateConfigurationCipherResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Missing password or invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationCipher tool (Status: 401, Content-Type: application/json)
const CreateConfigurationCipherResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Authentication required\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationCipher tool (Status: 403, Content-Type: application/json)
const CreateConfigurationCipherResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Insufficient permissions\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationCipher tool (Status: 500, Content-Type: application/json)
const CreateConfigurationCipherResponseTemplate_E = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 500\n\n**Content-Type:** application/json\n\n> Failed to set cipher password\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewCreateConfigurationCipherMCPTool creates the MCP Tool instance for CreateConfigurationCipher
func NewCreateConfigurationCipherMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateConfigurationCipher",
		"Set migration cipher password for decrypting imported secrets",
		[]byte(CreateConfigurationCipherInputSchema),
	)
}

// CreateConfigurationCipherHandler is the handler function for the CreateConfigurationCipher tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateConfigurationCipherHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "text/plain"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/configuration/cipher", args, []string{}, contentType, "CreateConfigurationCipher")
}
