// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateEmailVerify tool
const CreateEmailVerifyInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"An email address to send a test email to\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateEmailVerify tool (Status: 200, Content-Type: application/json)
const CreateEmailVerifyResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Test email was sent successfully\n\n## Response Structure\n\n- Structure (Type: object):\n  - **reason** (Type: string):\n  - **success** (Type: boolean):\n"

// Response Template for the CreateEmailVerify tool (Status: 400, Content-Type: application/json)
const CreateEmailVerifyResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> There was a problem sending the test email\n\n## Response Structure\n\n- Structure (Type: object):\n  - **reason** (Type: string):\n  - **success** (Type: boolean):\n"

// NewCreateEmailVerifyMCPTool creates the MCP Tool instance for CreateEmailVerify
func NewCreateEmailVerifyMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateEmailVerify",
		"Send a test email to the email address provided in the request body",
		[]byte(CreateEmailVerifyInputSchema),
	)
}

// CreateEmailVerifyHandler is the handler function for the CreateEmailVerify tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateEmailVerifyHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "*/*"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/email/verify", args, []string{}, contentType, "CreateEmailVerify")
}
