// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeletePlan_065c1589 tool
const DeletePlan_065c1589InputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeletePlan_065c1589MCPTool creates the MCP Tool instance for DeletePlan_065c1589
func NewDeletePlan_065c1589MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeletePlan_065c1589",
		"Delete all non executed reconciliation plans",
		[]byte(DeletePlan_065c1589InputSchema),
	)
}

// DeletePlan_065c1589Handler is the handler function for the DeletePlan_065c1589 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeletePlan_065c1589Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/plan/{planId}", args, []string{"planId"}, contentType, "DeletePlan_065c1589")
}
