// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteScript tool
const DeleteScriptInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteScriptMCPTool creates the MCP Tool instance for DeleteScript
func NewDeleteScriptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteScript",
		"Delete stored script by name",
		[]byte(DeleteScriptInputSchema),
	)
}

// DeleteScriptHandler is the handler function for the DeleteScript tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteScriptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/script/{name}", args, []string{"name"}, contentType, "DeleteScript")
}
