// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteTasks tool
const DeleteTasksInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteTasksMCPTool creates the MCP Tool instance for DeleteTasks
func NewDeleteTasksMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteTasks",
		"Delete task by id",
		[]byte(DeleteTasksInputSchema),
	)
}

// DeleteTasksHandler is the handler function for the DeleteTasks tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteTasksHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/tasks/{id}", args, []string{"id"}, contentType, "DeleteTasks")
}
