// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSystemNode tool
const DeleteSystemNodeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteSystemNodeMCPTool creates the MCP Tool instance for DeleteSystemNode
func NewDeleteSystemNodeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSystemNode",
		"Reset the ID for this node. Takes effect after restart and should only be used when cloning an instance",
		[]byte(DeleteSystemNodeInputSchema),
	)
}

// DeleteSystemNodeHandler is the handler function for the DeleteSystemNode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSystemNodeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/system/node", args, []string{}, contentType, "DeleteSystemNode")
}
