// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRepositories tool
const DeleteRepositoriesInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRepositoriesMCPTool creates the MCP Tool instance for DeleteRepositories
func NewDeleteRepositoriesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRepositories",
		"Delete repository of any format",
		[]byte(DeleteRepositoriesInputSchema),
	)
}

// DeleteRepositoriesHandler is the handler function for the DeleteRepositories tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRepositoriesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/repositories/{repositoryName}", args, []string{"repositoryName"}, contentType, "DeleteRepositories")
}
