// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteAssets tool
const DeleteAssetsInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the asset to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteAssetsMCPTool creates the MCP Tool instance for DeleteAssets
func NewDeleteAssetsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteAssets",
		"Delete a single asset",
		[]byte(DeleteAssetsInputSchema),
	)
}

// DeleteAssetsHandler is the handler function for the DeleteAssets tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteAssetsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/assets/{id}", args, []string{"id"}, contentType, "DeleteAssets")
}
