// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeletePlan_6a71b722 tool
const DeletePlan_6a71b722InputSchema = "{\n  \"properties\": {\n    \"planId\": {\n      \"description\": \"Id of the plan to delete\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"planId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeletePlan_6a71b722MCPTool creates the MCP Tool instance for DeletePlan_6a71b722
func NewDeletePlan_6a71b722MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeletePlan_6a71b722",
		"Delete a reconciliation plan based on its Id",
		[]byte(DeletePlan_6a71b722InputSchema),
	)
}

// DeletePlan_6a71b722Handler is the handler function for the DeletePlan_6a71b722 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeletePlan_6a71b722Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/plan", args, []string{}, contentType, "DeletePlan_6a71b722")
}
