// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityPrivileges tool
const DeleteSecurityPrivilegesInputSchema = "{\n  \"properties\": {\n    \"privilegeName\": {\n      \"description\": \"The name of the privilege to delete.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"privilegeName\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSecurityPrivilegesMCPTool creates the MCP Tool instance for DeleteSecurityPrivileges
func NewDeleteSecurityPrivilegesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityPrivileges",
		"Delete a privilege by name.",
		[]byte(DeleteSecurityPrivilegesInputSchema),
	)
}

// DeleteSecurityPrivilegesHandler is the handler function for the DeleteSecurityPrivileges tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityPrivilegesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/privileges/{privilegeName}", args, []string{"privilegeName"}, contentType, "DeleteSecurityPrivileges")
}
