// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityLdap tool
const DeleteSecurityLdapInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"Name of the LDAP server to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSecurityLdapMCPTool creates the MCP Tool instance for DeleteSecurityLdap
func NewDeleteSecurityLdapMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityLdap",
		"Delete LDAP server",
		[]byte(DeleteSecurityLdapInputSchema),
	)
}

// DeleteSecurityLdapHandler is the handler function for the DeleteSecurityLdap tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityLdapHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/ldap/{name}", args, []string{"name"}, contentType, "DeleteSecurityLdap")
}
