// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRepositoriesHealthCheck tool
const DeleteRepositoriesHealthCheckInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to disable Repository Health Check for\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRepositoriesHealthCheckMCPTool creates the MCP Tool instance for DeleteRepositoriesHealthCheck
func NewDeleteRepositoriesHealthCheckMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRepositoriesHealthCheck",
		"Disable repository health check. Proxy repositories only.",
		[]byte(DeleteRepositoriesHealthCheckInputSchema),
	)
}

// DeleteRepositoriesHealthCheckHandler is the handler function for the DeleteRepositoriesHealthCheck tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRepositoriesHealthCheckHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/repositories/{repositoryName}/health-check", args, []string{"repositoryName"}, contentType, "DeleteRepositoriesHealthCheck")
}
