// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetBlobstoresFile tool
const GetBlobstoresFileInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"The name of the file blob store to read\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetBlobstoresFile tool (Status: 200, Content-Type: application/json)
const GetBlobstoresFileResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Success\n\n## Response Structure\n\n- Structure (Type: object):\n  - **path**: An absolute path or a path relative to <data-directory>/blobs (Type: string):\n      - Min Length: 1\n  - **softQuota**: Settings to control the soft quota. (Type: object):\n    - **limit**: The limit in MB. (Type: integer, int64):\n        - Minimum: 0\n    - **type**: The type to use such as spaceRemainingQuota, or spaceUsedQuotaspaceUsedQuota (Type: string):\n        - Min Length: 1\n  - **softQuotaAttributes** (Type: object):\n    - **attributes** (Type: object):\n      - **Additional Properties**:\n        - **property value** (Type: object):\n          - **Additional Properties**:\n            - **property value** (Type: object):\n    - **name** (Type: string):\n    - **type** (Type: string):\n    - **writable** (Type: boolean):\n"

// NewGetBlobstoresFileMCPTool creates the MCP Tool instance for GetBlobstoresFile
func NewGetBlobstoresFileMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetBlobstoresFile",
		"Get a file blob store configuration by name",
		[]byte(GetBlobstoresFileInputSchema),
	)
}

// GetBlobstoresFileHandler is the handler function for the GetBlobstoresFile tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetBlobstoresFileHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/blobstores/file/{name}", args, []string{"name"}, contentType, "GetBlobstoresFile")
}
