// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetFormatsUploadSpecs tool
const GetFormatsUploadSpecsInputSchema = "{\n  \"properties\": {\n    \"format\": {\n      \"description\": \"The desired repository format\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"format\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetFormatsUploadSpecs tool (Status: 0, Content-Type: application/json)
const GetFormatsUploadSpecsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: object):\n  - **assetFields** (Type: array):\n    - **Items** (Type: object):\n      - **description** (Type: string):\n      - **group** (Type: string):\n      - **groupHelpText** (Type: string):\n      - **name** (Type: string):\n      - **optional** (Type: boolean):\n      - **options** (Type: object):\n        - **Additional Properties**:\n          - **property value** (Type: string):\n      - **type** (Type: string):\n  - **componentFields** (Type: array):\n    - **[cyclic reference]**\n  - **format** (Type: string):\n  - **multipleUpload** (Type: boolean):\n"

// NewGetFormatsUploadSpecsMCPTool creates the MCP Tool instance for GetFormatsUploadSpecs
func NewGetFormatsUploadSpecsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetFormatsUploadSpecs",
		"Get upload field requirements for the desired format",
		[]byte(GetFormatsUploadSpecsInputSchema),
	)
}

// GetFormatsUploadSpecsHandler is the handler function for the GetFormatsUploadSpecs tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetFormatsUploadSpecsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/formats/{format}/upload-specs", args, []string{"format"}, contentType, "GetFormatsUploadSpecs")
}
