// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetIqAudit tool
const GetIqAuditInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetIqAuditMCPTool creates the MCP Tool instance for GetIqAudit
func NewGetIqAuditMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetIqAudit",
		"Get audit status for the repository",
		[]byte(GetIqAuditInputSchema),
	)
}

// GetIqAuditHandler is the handler function for the GetIqAudit tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetIqAuditHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/iq/audit/{repositoryName}", args, []string{"repositoryName"}, contentType, "GetIqAudit")
}
