// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetPlan tool
const GetPlanInputSchema = "{\n  \"properties\": {\n    \"continuationToken\": {\n      \"description\": \"A token returned by a prior request. If present, the next page of results are returned\",\n      \"type\": \"string\"\n    },\n    \"planId\": {\n      \"description\": \"Id of the plan\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"repository\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"planId\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetPlanMCPTool creates the MCP Tool instance for GetPlan
func NewGetPlanMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetPlan",
		"Get single reconciliation plan with details",
		[]byte(GetPlanInputSchema),
	)
}

// GetPlanHandler is the handler function for the GetPlan tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetPlanHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/plan/{planId}", args, []string{"planId"}, contentType, "GetPlan")
}
