// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRepositories tool
const GetRepositoriesInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to get\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetRepositoriesMCPTool creates the MCP Tool instance for GetRepositories
func NewGetRepositoriesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRepositories",
		"Get repository details",
		[]byte(GetRepositoriesInputSchema),
	)
}

// GetRepositoriesHandler is the handler function for the GetRepositories tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRepositoriesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/repositories/{repositoryName}", args, []string{"repositoryName"}, contentType, "GetRepositories")
}
