// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRepositoriesBrowse tool
const GetRepositoriesBrowseInputSchema = "{\n  \"properties\": {\n    \"path\": {\n      \"description\": \"Path within the repository (URL-encoded, use '/' as separator). Use '/' for root.\",\n      \"type\": \"string\"\n    },\n    \"repositoryName\": {\n      \"description\": \"Repository name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetRepositoriesBrowse tool (Status: 200, Content-Type: application/json)
const GetRepositoriesBrowseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Browse nodes returned\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **assetId** (Type: string):\n    - **componentId** (Type: string):\n    - **id** (Type: string):\n        - Min Length: 1\n    - **leaf** (Type: boolean):\n    - **packageUrl** (Type: string):\n    - **text** (Type: string):\n        - Min Length: 1\n    - **type** (Type: string):\n        - Min Length: 1\n"

// NewGetRepositoriesBrowseMCPTool creates the MCP Tool instance for GetRepositoriesBrowse
func NewGetRepositoriesBrowseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRepositoriesBrowse",
		"List browse nodes for a repository path",
		[]byte(GetRepositoriesBrowseInputSchema),
	)
}

// GetRepositoriesBrowseHandler is the handler function for the GetRepositoriesBrowse tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRepositoriesBrowseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/repositories/{repositoryName}/browse", args, []string{"repositoryName"}, contentType, "GetRepositoriesBrowse")
}
