// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRoutingRules tool
const GetRoutingRulesInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"The name of the routing rule to get\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetRoutingRulesMCPTool creates the MCP Tool instance for GetRoutingRules
func NewGetRoutingRulesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRoutingRules",
		"Get a single routing rule",
		[]byte(GetRoutingRulesInputSchema),
	)
}

// GetRoutingRulesHandler is the handler function for the GetRoutingRules tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRoutingRulesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/routing-rules/{name}", args, []string{"name"}, contentType, "GetRoutingRules")
}
