// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetScript tool
const GetScriptInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetScriptMCPTool creates the MCP Tool instance for GetScript
func NewGetScriptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetScript",
		"Read stored script by name",
		[]byte(GetScriptInputSchema),
	)
}

// GetScriptHandler is the handler function for the GetScript tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetScriptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/script/{name}", args, []string{"name"}, contentType, "GetScript")
}
