// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityRealmsAvailable tool
const ListSecurityRealmsAvailableInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListSecurityRealmsAvailable tool (Status: 0, Content-Type: application/json)
const ListSecurityRealmsAvailableResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **id** (Type: string):\n    - **name** (Type: string):\n"

// NewListSecurityRealmsAvailableMCPTool creates the MCP Tool instance for ListSecurityRealmsAvailable
func NewListSecurityRealmsAvailableMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityRealmsAvailable",
		"List the available realms",
		[]byte(ListSecurityRealmsAvailableInputSchema),
	)
}

// ListSecurityRealmsAvailableHandler is the handler function for the ListSecurityRealmsAvailable tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityRealmsAvailableHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/realms/available", args, []string{}, contentType, "ListSecurityRealmsAvailable")
}
