// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListBlobstores tool
const ListBlobstoresInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListBlobstores tool (Status: 0, Content-Type: application/json)
const ListBlobstoresResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **availableSpaceInBytes** (Type: integer, int64):\n    - **blobCount** (Type: integer, int64):\n    - **name** (Type: string):\n    - **softQuota**: Settings to control the soft quota. (Type: object):\n      - **limit**: The limit in MB. (Type: integer, int64):\n          - Minimum: 0\n      - **type**: The type to use such as spaceRemainingQuota, or spaceUsedQuotaspaceUsedQuota (Type: string):\n          - Min Length: 1\n    - **softQuotaAttributes** (Type: object):\n      - **attributes** (Type: object):\n        - **Additional Properties**:\n          - **property value** (Type: object):\n            - **Additional Properties**:\n              - **property value** (Type: object):\n      - **name** (Type: string):\n      - **type** (Type: string):\n      - **writable** (Type: boolean):\n    - **totalSizeInBytes** (Type: integer, int64):\n    - **type** (Type: string):\n    - **unavailable** (Type: boolean):\n"

// NewListBlobstoresMCPTool creates the MCP Tool instance for ListBlobstores
func NewListBlobstoresMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListBlobstores",
		"List the blob stores",
		[]byte(ListBlobstoresInputSchema),
	)
}

// ListBlobstoresHandler is the handler function for the ListBlobstores tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListBlobstoresHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/blobstores", args, []string{}, contentType, "ListBlobstores")
}
