// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityUsers tool
const ListSecurityUsersInputSchema = "{\n  \"properties\": {\n    \"source\": {\n      \"description\": \"An optional user source to restrict the search to.\",\n      \"type\": \"string\"\n    },\n    \"userId\": {\n      \"description\": \"An optional term to search userids for.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewListSecurityUsersMCPTool creates the MCP Tool instance for ListSecurityUsers
func NewListSecurityUsersMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityUsers",
		"Retrieve a list of users. For SAML user sources a limit of 1000 users will be applied.",
		[]byte(ListSecurityUsersInputSchema),
	)
}

// ListSecurityUsersHandler is the handler function for the ListSecurityUsers tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityUsersHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/users", args, []string{}, contentType, "ListSecurityUsers")
}
