// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListConfigurationAssets tool
const ListConfigurationAssetsInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    },\n    \"continuationToken\": {\n      \"description\": \"A token returned by a prior request. If present, the next page of results are returned\",\n      \"type\": \"string\"\n    },\n    \"newerThan\": {\n      \"description\": \"Unix timestamp (milliseconds since epoch). Return assets last updated after this timestamp\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    },\n    \"olderThan\": {\n      \"description\": \"Unix timestamp (milliseconds since epoch). Return assets last updated before this timestamp\",\n      \"format\": \"int64\",\n      \"type\": \"integer\"\n    },\n    \"repository\": {\n      \"description\": \"Repository from which you would like to retrieve assets.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\",\n    \"repository\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the ListConfigurationAssets tool (Status: 200, Content-Type: application/json)
const ListConfigurationAssetsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful Operation\n\n## Response Structure\n\n- Structure (Type: object):\n  - **continuationToken** (Type: string):\n  - **items** (Type: array):\n    - **Items** (Type: object):\n"

// Response Template for the ListConfigurationAssets tool (Status: 400, Content-Type: application/json)
const ListConfigurationAssetsResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Missing or invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewListConfigurationAssetsMCPTool creates the MCP Tool instance for ListConfigurationAssets
func NewListConfigurationAssetsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListConfigurationAssets",
		"List assets",
		[]byte(ListConfigurationAssetsInputSchema),
	)
}

// ListConfigurationAssetsHandler is the handler function for the ListConfigurationAssets tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListConfigurationAssetsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/configuration/assets", args, []string{}, contentType, "ListConfigurationAssets")
}
