// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityRealmsActive tool
const ListSecurityRealmsActiveInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListSecurityRealmsActive tool (Status: 0, Content-Type: application/json)
const ListSecurityRealmsActiveResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: string):\n"

// NewListSecurityRealmsActiveMCPTool creates the MCP Tool instance for ListSecurityRealmsActive
func NewListSecurityRealmsActiveMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityRealmsActive",
		"List the active realm IDs in order",
		[]byte(ListSecurityRealmsActiveInputSchema),
	)
}

// ListSecurityRealmsActiveHandler is the handler function for the ListSecurityRealmsActive tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityRealmsActiveHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/realms/active", args, []string{}, contentType, "ListSecurityRealmsActive")
}
