// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListStatusCheck tool
const ListStatusCheckInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListStatusCheckMCPTool creates the MCP Tool instance for ListStatusCheck
func NewListStatusCheckMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListStatusCheck",
		"Health check endpoint that returns the results of the system status checks",
		[]byte(ListStatusCheckInputSchema),
	)
}

// ListStatusCheckHandler is the handler function for the ListStatusCheck tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListStatusCheckHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/status/check", args, []string{}, contentType, "ListStatusCheck")
}
