// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListComponents tool
const ListComponentsInputSchema = "{\n  \"properties\": {\n    \"continuationToken\": {\n      \"description\": \"A token returned by a prior request. If present, the next page of results are returned\",\n      \"type\": \"string\"\n    },\n    \"repository\": {\n      \"description\": \"Repository from which you would like to retrieve components\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repository\"\n  ],\n  \"type\": \"object\"\n}"

// NewListComponentsMCPTool creates the MCP Tool instance for ListComponents
func NewListComponentsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListComponents",
		"List components",
		[]byte(ListComponentsInputSchema),
	)
}

// ListComponentsHandler is the handler function for the ListComponents tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListComponentsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/components", args, []string{}, contentType, "ListComponents")
}
