// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListInternalCleanupPolicies tool
const ListInternalCleanupPoliciesInputSchema = "{\n  \"properties\": {\n    \"format\": {\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the ListInternalCleanupPolicies tool (Status: 200, Content-Type: application/json)
const ListInternalCleanupPoliciesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Cleanup policies matching the request\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **criteriaAssetRegex** (Type: string):\n    - **criteriaLastBlobUpdated** (Type: integer, int64):\n    - **criteriaLastDownloaded** (Type: integer, int64):\n    - **criteriaReleaseType** (Type: string):\n        - Enum: ['RELEASES', 'PRERELEASES']\n    - **format** (Type: string):\n        - Min Length: 1\n    - **inUseCount** (Type: integer, int32):\n    - **name** (Type: string):\n        - Max Length: 255\n        - Pattern: '^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$'\n    - **notes** (Type: string):\n    - **repositories** (Type: array):\n      - **Items** (Type: string):\n          - Min Length: 1\n    - **retain** (Type: integer, int32):\n        - Minimum: 1\n    - **sortBy** (Type: string):\n"

// NewListInternalCleanupPoliciesMCPTool creates the MCP Tool instance for ListInternalCleanupPolicies
func NewListInternalCleanupPoliciesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListInternalCleanupPolicies",
		"List cleanup policies - Returns all configured cleanup policies sorted by name. Pass the optional "+"\x60"+"format"+"\x60"+" query parameter to return only policies for that format (e.g. "+"\x60"+"maven2"+"\x60"+", "+"\x60"+"npm"+"\x60"+", "+"\x60"+"docker"+"\x60"+"); omit it or pass "+"\x60"+"*"+"\x60"+" to return policies across all formats. Each entry includes the policy definition and the number of repositories currently using it.",
		[]byte(ListInternalCleanupPoliciesInputSchema),
	)
}

// ListInternalCleanupPoliciesHandler is the handler function for the ListInternalCleanupPolicies tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListInternalCleanupPoliciesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/internal/cleanup-policies", args, []string{}, contentType, "ListInternalCleanupPolicies")
}
