// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListInternalUiApiPermissions tool
const ListInternalUiApiPermissionsInputSchema = "{\n  \"properties\": {\n    \"method\": {\n      \"type\": \"string\"\n    },\n    \"path\": {\n      \"type\": \"string\"\n    },\n    \"permission\": {\n      \"type\": \"string\"\n    },\n    \"tag\": {\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the ListInternalUiApiPermissions tool (Status: 200, Content-Type: application/json)
const ListInternalUiApiPermissionsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Permission map\n\n## Response Structure\n\n- Structure (Type: object):\n  - **endpoints**: Mapped endpoints (Type: array):\n    - **Items**: Mapped endpoints (Type: object):\n      - **authenticated**: Whether the endpoint requires an authenticated subject (Type: boolean):\n      - **description**: Short description from Swagger annotations, if any (Type: string):\n      - **httpMethod**: HTTP method (Type: string):\n          - Example: 'DELETE'\n      - **pathPattern**: Path pattern with JAX-RS template segments (Type: string):\n      - **permissions**: Required permissions and combination logic (Type: array):\n        - **Items**: Required permissions and combination logic (Type: object):\n          - **logical**: How this permission combines with siblings (AND or OR) (Type: string):\n          - **permission**: Permission string as declared on the resource (Type: string):\n      - **tag**: Swagger tag / API grouping (Type: string):\n  - **error**: Present when the registry could not serve data (Type: string):\n  - **generatedAt**: ISO-8601 timestamp when the registry was built (Type: string):\n  - **totalEndpoints**: Total endpoints returned before client-side filtering (Type: integer, int32):\n  - **unmappedEndpoints**: Count of Swagger operations that had no permission mapping at registry build time (Type: integer, int32):\n"

// NewListInternalUiApiPermissionsMCPTool creates the MCP Tool instance for ListInternalUiApiPermissions
func NewListInternalUiApiPermissionsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListInternalUiApiPermissions",
		"List REST endpoints with permission metadata for the API documentation UI",
		[]byte(ListInternalUiApiPermissionsInputSchema),
	)
}

// ListInternalUiApiPermissionsHandler is the handler function for the ListInternalUiApiPermissions tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListInternalUiApiPermissionsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/internal/ui/api/permissions", args, []string{}, contentType, "ListInternalUiApiPermissions")
}
