// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListDataStore tool
const ListDataStoreInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListDataStoreMCPTool creates the MCP Tool instance for ListDataStore
func NewListDataStoreMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListDataStore",
		"Get the data store",
		[]byte(ListDataStoreInputSchema),
	)
}

// ListDataStoreHandler is the handler function for the ListDataStore tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListDataStoreHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/beta/data-store", args, []string{}, contentType, "ListDataStore")
}
