// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListLifecyclePhase tool
const ListLifecyclePhaseInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListLifecyclePhase tool (Status: 0, Content-Type: text/plain)
const ListLifecyclePhaseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** text/plain\n\n> default response\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewListLifecyclePhaseMCPTool creates the MCP Tool instance for ListLifecyclePhase
func NewListLifecyclePhaseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListLifecyclePhase",
		"Get current lifecycle phase",
		[]byte(ListLifecyclePhaseInputSchema),
	)
}

// ListLifecyclePhaseHandler is the handler function for the ListLifecyclePhase tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListLifecyclePhaseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/lifecycle/phase", args, []string{}, contentType, "ListLifecyclePhase")
}
