// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSystemEula tool
const ListSystemEulaInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSystemEulaMCPTool creates the MCP Tool instance for ListSystemEula
func NewListSystemEulaMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSystemEula",
		"Get the current Community Eula status.",
		[]byte(ListSystemEulaInputSchema),
	)
}

// ListSystemEulaHandler is the handler function for the ListSystemEula tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSystemEulaHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/system/eula", args, []string{}, contentType, "ListSystemEula")
}
