// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateLifecyclePhase tool
const UpdateLifecyclePhaseInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The phase to move to\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateLifecyclePhaseMCPTool creates the MCP Tool instance for UpdateLifecyclePhase
func NewUpdateLifecyclePhaseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateLifecyclePhase",
		"Move to new lifecycle phase",
		[]byte(UpdateLifecyclePhaseInputSchema),
	)
}

// UpdateLifecyclePhaseHandler is the handler function for the UpdateLifecyclePhase tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateLifecyclePhaseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "text/plain"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/lifecycle/phase", args, []string{}, contentType, "UpdateLifecyclePhase")
}
