// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityPrivilegesWildcard tool
const UpdateSecurityPrivilegesWildcardInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The privilege to update.\",\n      \"properties\": {\n        \"description\": {\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the privilege.  This value cannot be changed.\",\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"pattern\": {\n          \"description\": \"A colon separated list of parts that create a permission string.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"name\",\n        \"pattern\"\n      ],\n      \"type\": \"object\"\n    },\n    \"privilegeName\": {\n      \"description\": \"The name of the privilege to update.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"privilegeName\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateSecurityPrivilegesWildcardMCPTool creates the MCP Tool instance for UpdateSecurityPrivilegesWildcard
func NewUpdateSecurityPrivilegesWildcardMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityPrivilegesWildcard",
		"Update a wildcard type privilege.",
		[]byte(UpdateSecurityPrivilegesWildcardInputSchema),
	)
}

// UpdateSecurityPrivilegesWildcardHandler is the handler function for the UpdateSecurityPrivilegesWildcard tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityPrivilegesWildcardHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/privileges/wildcard/{privilegeName}", args, []string{"privilegeName"}, contentType, "UpdateSecurityPrivilegesWildcard")
}
