// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateScript tool
const UpdateScriptInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"content\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"type\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"content\",\n        \"name\",\n        \"type\"\n      ],\n      \"type\": \"object\"\n    },\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateScriptMCPTool creates the MCP Tool instance for UpdateScript
func NewUpdateScriptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateScript",
		"Update stored script by name",
		[]byte(UpdateScriptInputSchema),
	)
}

// UpdateScriptHandler is the handler function for the UpdateScript tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateScriptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/script/{name}", args, []string{"name"}, contentType, "UpdateScript")
}
