// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityContentSelectors tool
const UpdateSecurityContentSelectorsInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"description\": {\n          \"description\": \"An optional description of this content selector\",\n          \"type\": \"string\"\n        },\n        \"expression\": {\n          \"description\": \"The expression used to identify content\",\n          \"example\": \"format == \\\"maven2\\\" and path =^ \\\"/org/sonatype/nexus\\\"\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"expression\"\n      ],\n      \"type\": \"object\"\n    },\n    \"name\": {\n      \"description\": \"The content selector name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateSecurityContentSelectorsMCPTool creates the MCP Tool instance for UpdateSecurityContentSelectors
func NewUpdateSecurityContentSelectorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityContentSelectors",
		"Update a content selector",
		[]byte(UpdateSecurityContentSelectorsInputSchema),
	)
}

// UpdateSecurityContentSelectorsHandler is the handler function for the UpdateSecurityContentSelectors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityContentSelectorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/content-selectors/{name}", args, []string{"name"}, contentType, "UpdateSecurityContentSelectors")
}
