// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdatePlan_7f3759ad tool
const UpdatePlan_7f3759adInputSchema = "{\n  \"properties\": {\n    \"planId\": {\n      \"description\": \"Id of the plan to execute\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    }\n  },\n  \"required\": [\n    \"planId\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdatePlan_7f3759adMCPTool creates the MCP Tool instance for UpdatePlan_7f3759ad
func NewUpdatePlan_7f3759adMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdatePlan_7f3759ad",
		"Execute a reconciliation plan based on its Id",
		[]byte(UpdatePlan_7f3759adInputSchema),
	)
}

// UpdatePlan_7f3759adHandler is the handler function for the UpdatePlan_7f3759ad tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdatePlan_7f3759adHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/plan/{planId}", args, []string{"planId"}, contentType, "UpdatePlan_7f3759ad")
}
