// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateInternalCleanupPolicies tool
const UpdateInternalCleanupPoliciesInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"criteriaAssetRegex\": {\n          \"type\": \"string\"\n        },\n        \"criteriaLastBlobUpdated\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"criteriaLastDownloaded\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"criteriaReleaseType\": {\n          \"enum\": [\n            \"RELEASES\",\n            \"PRERELEASES\"\n          ],\n          \"type\": \"string\"\n        },\n        \"format\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"inUseCount\": {\n          \"format\": \"int32\",\n          \"type\": \"integer\"\n        },\n        \"name\": {\n          \"maxLength\": 255,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"notes\": {\n          \"type\": \"string\"\n        },\n        \"repositories\": {\n          \"items\": {\n            \"minLength\": 1,\n            \"type\": \"string\"\n          },\n          \"type\": \"array\"\n        },\n        \"retain\": {\n          \"format\": \"int32\",\n          \"minimum\": 1,\n          \"type\": \"integer\"\n        },\n        \"sortBy\": {\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"format\",\n        \"name\"\n      ],\n      \"type\": \"object\"\n    },\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the UpdateInternalCleanupPolicies tool (Status: 0, Content-Type: application/json)
const UpdateInternalCleanupPoliciesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: object):\n  - **criteriaAssetRegex** (Type: string):\n  - **criteriaLastBlobUpdated** (Type: integer, int64):\n  - **criteriaLastDownloaded** (Type: integer, int64):\n  - **criteriaReleaseType** (Type: string):\n      - Enum: ['RELEASES', 'PRERELEASES']\n  - **format** (Type: string):\n      - Min Length: 1\n  - **inUseCount** (Type: integer, int32):\n  - **name** (Type: string):\n      - Max Length: 255\n      - Pattern: '^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$'\n  - **notes** (Type: string):\n  - **repositories** (Type: array):\n    - **Items** (Type: string):\n        - Min Length: 1\n  - **retain** (Type: integer, int32):\n      - Minimum: 1\n  - **sortBy** (Type: string):\n"

// NewUpdateInternalCleanupPoliciesMCPTool creates the MCP Tool instance for UpdateInternalCleanupPolicies
func NewUpdateInternalCleanupPoliciesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateInternalCleanupPolicies",
		"",
		[]byte(UpdateInternalCleanupPoliciesInputSchema),
	)
}

// UpdateInternalCleanupPoliciesHandler is the handler function for the UpdateInternalCleanupPolicies tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateInternalCleanupPoliciesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/internal/cleanup-policies/{name}", args, []string{"name"}, contentType, "UpdateInternalCleanupPolicies")
}
