// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateEmail tool
const UpdateEmailInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"enabled\": {\n          \"type\": \"boolean\"\n        },\n        \"fromAddress\": {\n          \"example\": \"nexus@example.org\",\n          \"format\": \"email\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"host\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"nexusTrustStoreEnabled\": {\n          \"description\": \"Use the Nexus Repository Manager's certificate truststore\",\n          \"type\": \"boolean\"\n        },\n        \"password\": {\n          \"type\": \"string\"\n        },\n        \"port\": {\n          \"format\": \"int32\",\n          \"type\": \"integer\"\n        },\n        \"sslOnConnectEnabled\": {\n          \"description\": \"Enable SSL/TLS Encryption upon Connection\",\n          \"type\": \"boolean\"\n        },\n        \"sslServerIdentityCheckEnabled\": {\n          \"description\": \"Verify the server certificate when using TLS or SSL\",\n          \"type\": \"boolean\"\n        },\n        \"startTlsEnabled\": {\n          \"description\": \"Enable STARTTLS Support for Insecure Connections\",\n          \"type\": \"boolean\"\n        },\n        \"startTlsRequired\": {\n          \"description\": \"Require STARTTLS Support\",\n          \"type\": \"boolean\"\n        },\n        \"subjectPrefix\": {\n          \"description\": \"A prefix to add to all email subjects to aid in identifying automated emails\",\n          \"type\": \"string\"\n        },\n        \"username\": {\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"fromAddress\",\n        \"host\",\n        \"port\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateEmailMCPTool creates the MCP Tool instance for UpdateEmail
func NewUpdateEmailMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateEmail",
		"Set the current email configuration",
		[]byte(UpdateEmailInputSchema),
	)
}

// UpdateEmailHandler is the handler function for the UpdateEmail tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateEmailHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "*/*"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/email", args, []string{}, contentType, "UpdateEmail")
}
