// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateConfiguration tool
const UpdateConfigurationInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    },\n    \"body\": {\n      \"properties\": {\n        \"configurationXOs\": {\n          \"items\": {\n            \"properties\": {\n              \"configurationTypeId\": {\n                \"type\": \"string\"\n              }\n            },\n            \"type\": \"object\"\n          },\n          \"type\": \"array\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the UpdateConfiguration tool (Status: 200, Content-Type: application/json)
const UpdateConfigurationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful Operation\n\n## Response Structure\n\n- Structure (Type: object):\n  - **appliedConfigurations** (Type: array):\n    - **Items** (Type: object):\n      - **entity** (Type: string):\n      - **message** (Type: string):\n      - **status** (Type: string):\n          - Enum: ['APPLIED', 'NOT_APPLIED', 'FAILED']\n  - **failedConfigurations** (Type: array):\n    - **[cyclic reference]**\n  - **notAppliedConfigurations** (Type: array):\n    - **[cyclic reference]**\n"

// Response Template for the UpdateConfiguration tool (Status: 400, Content-Type: application/json)
const UpdateConfigurationResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Invalid request or missing/invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the UpdateConfiguration tool (Status: 401, Content-Type: application/json)
const UpdateConfigurationResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Authentication required\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the UpdateConfiguration tool (Status: 403, Content-Type: application/json)
const UpdateConfigurationResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Insufficient permissions\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewUpdateConfigurationMCPTool creates the MCP Tool instance for UpdateConfiguration
func NewUpdateConfigurationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateConfiguration",
		"Apply instance configuration",
		[]byte(UpdateConfigurationInputSchema),
	)
}

// UpdateConfigurationHandler is the handler function for the UpdateConfiguration tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateConfigurationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/configuration", args, []string{}, contentType, "UpdateConfiguration")
}
