// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateBlobstoresFile tool
const UpdateBlobstoresFileInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"path\": {\n          \"description\": \"An absolute path or a path relative to \\u003cdata-directory\\u003e/blobs\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"softQuota\": {\n          \"description\": \"Settings to control the soft quota.\",\n          \"properties\": {\n            \"limit\": {\n              \"description\": \"The limit in MB.\",\n              \"format\": \"int64\",\n              \"minimum\": 0,\n              \"type\": \"integer\"\n            },\n            \"type\": {\n              \"description\": \"The type to use such as spaceRemainingQuota, or spaceUsedQuotaspaceUsedQuota\",\n              \"minLength\": 1,\n              \"type\": \"string\"\n            }\n          },\n          \"required\": [\n            \"type\"\n          ],\n          \"type\": \"object\"\n        },\n        \"softQuotaAttributes\": {\n          \"properties\": {\n            \"attributes\": {\n              \"additionalProperties\": {\n                \"additionalProperties\": {\n                  \"type\": \"object\"\n                },\n                \"type\": \"object\"\n              },\n              \"type\": \"object\"\n            },\n            \"name\": {\n              \"type\": \"string\"\n            },\n            \"type\": {\n              \"type\": \"string\"\n            },\n            \"writable\": {\n              \"type\": \"boolean\"\n            }\n          },\n          \"type\": \"object\"\n        }\n      },\n      \"required\": [\n        \"path\"\n      ],\n      \"type\": \"object\"\n    },\n    \"name\": {\n      \"description\": \"The name of the file blob store to update\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateBlobstoresFileMCPTool creates the MCP Tool instance for UpdateBlobstoresFile
func NewUpdateBlobstoresFileMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateBlobstoresFile",
		"Update a file blob store configuration by name",
		[]byte(UpdateBlobstoresFileInputSchema),
	)
}

// UpdateBlobstoresFileHandler is the handler function for the UpdateBlobstoresFile tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateBlobstoresFileHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/blobstores/file/{name}", args, []string{"name"}, contentType, "UpdateBlobstoresFile")
}
