// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdatePlan_b0e3a2f5 tool
const UpdatePlan_b0e3a2f5InputSchema = "{\n  \"type\": \"object\"\n}"

// NewUpdatePlan_b0e3a2f5MCPTool creates the MCP Tool instance for UpdatePlan_b0e3a2f5
func NewUpdatePlan_b0e3a2f5MCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdatePlan_b0e3a2f5",
		"Execute all non executed reconciliation plans",
		[]byte(UpdatePlan_b0e3a2f5InputSchema),
	)
}

// UpdatePlan_b0e3a2f5Handler is the handler function for the UpdatePlan_b0e3a2f5 tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdatePlan_b0e3a2f5Handler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/plan/{planId}", args, []string{"planId"}, contentType, "UpdatePlan_b0e3a2f5")
}
