// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateCleanupRun tool
const CreateCleanupRunInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"dryRun\": {\n          \"type\": \"boolean\"\n        },\n        \"policy\": {\n          \"type\": \"string\"\n        },\n        \"repository\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"repository\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// Response Template for the CreateCleanupRun tool (Status: 200, Content-Type: application/json)
const CreateCleanupRunResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Dry run completed; " + "\x60" + "componentCount" + "\x60" + " reports how many components match\n\n## Response Structure\n\n- Structure (Type: object):\n  - **componentCount** (Type: integer, int64):\n  - **componentsDeleted** (Type: integer, int64):\n  - **dryRun** (Type: boolean):\n  - **durationMs** (Type: integer, int64):\n  - **error** (Type: string):\n  - **id** (Type: string):\n  - **policy** (Type: string):\n  - **repository** (Type: string):\n  - **status** (Type: string):\n      - Enum: ['RUNNING', 'COMPLETED', 'FAILED']\n"

// Response Template for the CreateCleanupRun tool (Status: 202, Content-Type: application/json)
const CreateCleanupRunResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 202\n\n**Content-Type:** application/json\n\n> Async cleanup accepted; use the returned " + "\x60" + "id" + "\x60" + " with GET /cleanup/run/{id} to poll for status\n\n## Response Structure\n\n- Structure (Type: object):\n  - **componentCount** (Type: integer, int64):\n  - **componentsDeleted** (Type: integer, int64):\n  - **dryRun** (Type: boolean):\n  - **durationMs** (Type: integer, int64):\n  - **error** (Type: string):\n  - **id** (Type: string):\n  - **policy** (Type: string):\n  - **repository** (Type: string):\n  - **status** (Type: string):\n      - Enum: ['RUNNING', 'COMPLETED', 'FAILED']\n"

// Response Template for the CreateCleanupRun tool (Status: 409, Content-Type: application/json)
const CreateCleanupRunResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 409\n\n**Content-Type:** application/json\n\n> A non-dry-run cleanup is already RUNNING for this repository; the response body is the existing execution's status\n\n## Response Structure\n\n- Structure (Type: object):\n  - **componentCount** (Type: integer, int64):\n  - **componentsDeleted** (Type: integer, int64):\n  - **dryRun** (Type: boolean):\n  - **durationMs** (Type: integer, int64):\n  - **error** (Type: string):\n  - **id** (Type: string):\n  - **policy** (Type: string):\n  - **repository** (Type: string):\n  - **status** (Type: string):\n      - Enum: ['RUNNING', 'COMPLETED', 'FAILED']\n"

// NewCreateCleanupRunMCPTool creates the MCP Tool instance for CreateCleanupRun
func NewCreateCleanupRunMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateCleanupRun",
		"Run cleanup on a repository (dry run or async execution) - Runs cleanup on the specified "+"\x60"+"repository"+"\x60"+" against the policies attached to it. Behavior depends on the "+"\x60"+"dryRun"+"\x60"+" flag in the request body:\n\n- "+"\x60"+"dryRun: true"+"\x60"+" — Synchronously evaluates the policies and returns **200 OK** with a "+"\x60"+"CleanupExecutionStatusXO"+"\x60"+" whose "+"\x60"+"componentCount"+"\x60"+" is the number of components that *would* be deleted. No components are removed.\n- "+"\x60"+"dryRun: false"+"\x60"+" — Schedules an asynchronous deletion and returns **202 Accepted** immediately with a "+"\x60"+"CleanupExecutionStatusXO"+"\x60"+" containing the generated execution "+"\x60"+"id"+"\x60"+" and "+"\x60"+"status=RUNNING"+"\x60"+". Poll "+"\x60"+"GET /service/rest/v1/cleanup/run/{id}"+"\x60"+" to observe the terminal "+"\x60"+"COMPLETED"+"\x60"+" or "+"\x60"+"FAILED"+"\x60"+" state and the final "+"\x60"+"componentsDeleted"+"\x60"+" count. Execution records are retained for 24 hours.\n\nAt most one non-dry-run cleanup may be "+"\x60"+"RUNNING"+"\x60"+" per repository. A second non-dry-run submitted while one is in progress is rejected with **409 Conflict** and the body of the existing execution's status.",
		[]byte(CreateCleanupRunInputSchema),
	)
}

// CreateCleanupRunHandler is the handler function for the CreateCleanupRun tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateCleanupRunHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/cleanup/run", args, []string{}, contentType, "CreateCleanupRun")
}
