// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateConfigurationAssetsImport tool
const CreateConfigurationAssetsImportInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    },\n    \"repositoryName\": {\n      \"description\": \"Repository name to import assets to\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\",\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateConfigurationAssetsImport tool (Status: 201, Content-Type: application/json)
const CreateConfigurationAssetsImportResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 201\n\n**Content-Type:** application/json\n\n> Assets imported successfully\n\n## Response Structure\n\n- Structure (Type: object):\n  - **assetId** (Type: string):\n  - **componentId** (Type: string):\n  - **errorMessage** (Type: string):\n  - **importTimestamp** (Type: string, date-time):\n  - **path** (Type: string):\n  - **repository** (Type: string):\n  - **status** (Type: string):\n      - Enum: ['SUCCESS', 'SUCCESS_WITH_WARNINGS', 'SKIPPED_ALREADY_EXISTS', 'FAILED']\n  - **warnings** (Type: array):\n    - **Items** (Type: string):\n"

// Response Template for the CreateConfigurationAssetsImport tool (Status: 400, Content-Type: application/json)
const CreateConfigurationAssetsImportResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Repository not found or missing/invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationAssetsImport tool (Status: 401, Content-Type: application/json)
const CreateConfigurationAssetsImportResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Authentication required\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationAssetsImport tool (Status: 403, Content-Type: application/json)
const CreateConfigurationAssetsImportResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Insufficient permissions\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationAssetsImport tool (Status: 500, Content-Type: application/json)
const CreateConfigurationAssetsImportResponseTemplate_E = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 500\n\n**Content-Type:** application/json\n\n> Asset import failed\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewCreateConfigurationAssetsImportMCPTool creates the MCP Tool instance for CreateConfigurationAssetsImport
func NewCreateConfigurationAssetsImportMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateConfigurationAssetsImport",
		"Import assets to repository",
		[]byte(CreateConfigurationAssetsImportInputSchema),
	)
}

// CreateConfigurationAssetsImportHandler is the handler function for the CreateConfigurationAssetsImport tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateConfigurationAssetsImportHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/configuration/assets/{repositoryName}/import", args, []string{"repositoryName"}, contentType, "CreateConfigurationAssetsImport")
}
