// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateTasksRun tool
const CreateTasksRunInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the task to run\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateTasksRunMCPTool creates the MCP Tool instance for CreateTasksRun
func NewCreateTasksRunMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateTasksRun",
		"Run task",
		[]byte(CreateTasksRunInputSchema),
	)
}

// CreateTasksRunHandler is the handler function for the CreateTasksRun tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateTasksRunHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/tasks/{id}/run", args, []string{"id"}, contentType, "CreateTasksRun")
}
