// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreatePlan tool
const CreatePlanInputSchema = "{\n  \"properties\": {\n    \"blobStores\": {\n      \"items\": {\n        \"type\": \"string\"\n      },\n      \"type\": \"array\"\n    },\n    \"endDate\": {\n      \"type\": \"string\"\n    },\n    \"repositories\": {\n      \"description\": \"repository(ies) which should be processed with high priority\",\n      \"items\": {\n        \"type\": \"string\"\n      },\n      \"type\": \"array\"\n    },\n    \"sinceDays\": {\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"sinceHours\": {\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"sinceMinutes\": {\n      \"default\": 30,\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"startDate\": {\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewCreatePlanMCPTool creates the MCP Tool instance for CreatePlan
func NewCreatePlanMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreatePlan",
		"Create reconciliation plans with selected parameters",
		[]byte(CreatePlanInputSchema),
	)
}

// CreatePlanHandler is the handler function for the CreatePlan tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreatePlanHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/plan", args, []string{}, contentType, "CreatePlan")
}
