// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateRecoveryMode tool
const CreateRecoveryModeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewCreateRecoveryModeMCPTool creates the MCP Tool instance for CreateRecoveryMode
func NewCreateRecoveryModeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateRecoveryMode",
		"Enables recovery mode and cancels conflicting tasks if running",
		[]byte(CreateRecoveryModeInputSchema),
	)
}

// CreateRecoveryModeHandler is the handler function for the CreateRecoveryMode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateRecoveryModeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/recovery-mode", args, []string{}, contentType, "CreateRecoveryMode")
}
