// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSupportSupportzippath tool
const CreateSupportSupportzippathInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"archivedLog\": {\n          \"format\": \"int32\",\n          \"type\": \"integer\"\n        },\n        \"auditLog\": {\n          \"type\": \"boolean\"\n        },\n        \"configuration\": {\n          \"type\": \"boolean\"\n        },\n        \"hostname\": {\n          \"type\": \"string\"\n        },\n        \"jmx\": {\n          \"type\": \"boolean\"\n        },\n        \"limitFileSizes\": {\n          \"type\": \"boolean\"\n        },\n        \"limitZipSize\": {\n          \"type\": \"boolean\"\n        },\n        \"log\": {\n          \"type\": \"boolean\"\n        },\n        \"metrics\": {\n          \"type\": \"boolean\"\n        },\n        \"replication\": {\n          \"type\": \"boolean\"\n        },\n        \"security\": {\n          \"type\": \"boolean\"\n        },\n        \"systemInformation\": {\n          \"type\": \"boolean\"\n        },\n        \"taskLog\": {\n          \"type\": \"boolean\"\n        },\n        \"threadDump\": {\n          \"type\": \"boolean\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewCreateSupportSupportzippathMCPTool creates the MCP Tool instance for CreateSupportSupportzippath
func NewCreateSupportSupportzippathMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSupportSupportzippath",
		"Creates a support zip and returns the path",
		[]byte(CreateSupportSupportzippathInputSchema),
	)
}

// CreateSupportSupportzippathHandler is the handler function for the CreateSupportSupportzippath tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSupportSupportzippathHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/support/supportzippath", args, []string{}, contentType, "CreateSupportSupportzippath")
}
