// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateConfigurationTransferComplete tool
const CreateConfigurationTransferCompleteInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    },\n    \"body\": {\n      \"description\": \"Transfer completion notification data\",\n      \"properties\": {\n        \"failedAssetTransferCount\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"message\": {\n          \"type\": \"string\"\n        },\n        \"repositoryName\": {\n          \"type\": \"string\"\n        },\n        \"skippedAssetTransferCount\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"successful\": {\n          \"type\": \"boolean\"\n        },\n        \"successfulAssetTransferCount\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        },\n        \"timestamp\": {\n          \"format\": \"int64\",\n          \"type\": \"integer\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\",\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the CreateConfigurationTransferComplete tool (Status: 200, Content-Type: application/json)
const CreateConfigurationTransferCompleteResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Transfer complete notification received\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationTransferComplete tool (Status: 400, Content-Type: application/json)
const CreateConfigurationTransferCompleteResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Missing notification data, repository name, or invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationTransferComplete tool (Status: 401, Content-Type: application/json)
const CreateConfigurationTransferCompleteResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Authentication required\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationTransferComplete tool (Status: 403, Content-Type: application/json)
const CreateConfigurationTransferCompleteResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Insufficient permissions\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the CreateConfigurationTransferComplete tool (Status: 500, Content-Type: application/json)
const CreateConfigurationTransferCompleteResponseTemplate_E = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 500\n\n**Content-Type:** application/json\n\n> Failed to process notification\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewCreateConfigurationTransferCompleteMCPTool creates the MCP Tool instance for CreateConfigurationTransferComplete
func NewCreateConfigurationTransferCompleteMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateConfigurationTransferComplete",
		"Receive transfer complete notification from migrator",
		[]byte(CreateConfigurationTransferCompleteInputSchema),
	)
}

// CreateConfigurationTransferCompleteHandler is the handler function for the CreateConfigurationTransferComplete tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateConfigurationTransferCompleteHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/configuration/transfer-complete", args, []string{}, contentType, "CreateConfigurationTransferComplete")
}
