// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateScript tool
const CreateScriptInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"content\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"type\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"content\",\n        \"name\",\n        \"type\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateScriptMCPTool creates the MCP Tool instance for CreateScript
func NewCreateScriptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateScript",
		"Add a new script",
		[]byte(CreateScriptInputSchema),
	)
}

// CreateScriptHandler is the handler function for the CreateScript tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateScriptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/script", args, []string{}, contentType, "CreateScript")
}
