// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityUsers tool
const CreateSecurityUsersInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"A representation of the user to create.\",\n      \"properties\": {\n        \"emailAddress\": {\n          \"description\": \"The email address associated with the user.\",\n          \"format\": \"email\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"firstName\": {\n          \"description\": \"The first name of the user.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"lastName\": {\n          \"description\": \"The last name of the user.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"password\": {\n          \"description\": \"The password for the new user.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"roles\": {\n          \"description\": \"The roles which the user has been assigned within Nexus.\",\n          \"items\": {\n            \"description\": \"The roles which the user has been assigned within Nexus.\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        },\n        \"status\": {\n          \"description\": \"The user's status, e.g. active or disabled.\",\n          \"enum\": [\n            \"active\",\n            \"locked\",\n            \"disabled\",\n            \"changepassword\"\n          ],\n          \"type\": \"string\"\n        },\n        \"userId\": {\n          \"description\": \"The userid which is required for login. This value cannot be changed.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"emailAddress\",\n        \"firstName\",\n        \"lastName\",\n        \"password\",\n        \"status\",\n        \"userId\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityUsersMCPTool creates the MCP Tool instance for CreateSecurityUsers
func NewCreateSecurityUsersMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityUsers",
		"Create a new user in the default source.",
		[]byte(CreateSecurityUsersInputSchema),
	)
}

// CreateSecurityUsersHandler is the handler function for the CreateSecurityUsers tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityUsersHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/users", args, []string{}, contentType, "CreateSecurityUsers")
}
