// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityPrivilegesScript tool
const CreateSecurityPrivilegesScriptInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The privilege to create.\",\n      \"properties\": {\n        \"actions\": {\n          \"description\": \"A collection of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.\",\n          \"items\": {\n            \"description\": \"A collection of actions to associate with the privilege, using BREAD syntax (browse,read,edit,add,delete,all) as well as 'run' for script privileges.\",\n            \"enum\": [\n              \"READ\",\n              \"BROWSE\",\n              \"EDIT\",\n              \"ADD\",\n              \"DELETE\",\n              \"RUN\",\n              \"START\",\n              \"STOP\",\n              \"ASSOCIATE\",\n              \"DISASSOCIATE\",\n              \"ALL\"\n            ],\n            \"type\": \"string\"\n          },\n          \"minItems\": 1,\n          \"type\": \"array\"\n        },\n        \"description\": {\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the privilege.  This value cannot be changed.\",\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"scriptName\": {\n          \"description\": \"The name of a script to give access to.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"actions\",\n        \"name\",\n        \"scriptName\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityPrivilegesScriptMCPTool creates the MCP Tool instance for CreateSecurityPrivilegesScript
func NewCreateSecurityPrivilegesScriptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityPrivilegesScript",
		"Create a script type privilege.",
		[]byte(CreateSecurityPrivilegesScriptInputSchema),
	)
}

// CreateSecurityPrivilegesScriptHandler is the handler function for the CreateSecurityPrivilegesScript tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityPrivilegesScriptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/privileges/script", args, []string{}, contentType, "CreateSecurityPrivilegesScript")
}
