// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateSecurityAtlassianCrowdVerifyConnection tool
const CreateSecurityAtlassianCrowdVerifyConnectionInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"applicationName\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"applicationPassword\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"enabled\": {\n          \"type\": \"boolean\"\n        },\n        \"realmActive\": {\n          \"type\": \"boolean\"\n        },\n        \"timeout\": {\n          \"format\": \"int32\",\n          \"maximum\": 3600,\n          \"minimum\": 1,\n          \"type\": \"integer\"\n        },\n        \"url\": {\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"useTrustStoreForUrl\": {\n          \"type\": \"boolean\"\n        }\n      },\n      \"required\": [\n        \"applicationName\",\n        \"applicationPassword\",\n        \"enabled\",\n        \"realmActive\",\n        \"url\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateSecurityAtlassianCrowdVerifyConnectionMCPTool creates the MCP Tool instance for CreateSecurityAtlassianCrowdVerifyConnection
func NewCreateSecurityAtlassianCrowdVerifyConnectionMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateSecurityAtlassianCrowdVerifyConnection",
		"Verify connection using supplied Atlassian Crowd settings",
		[]byte(CreateSecurityAtlassianCrowdVerifyConnectionInputSchema),
	)
}

// CreateSecurityAtlassianCrowdVerifyConnectionHandler is the handler function for the CreateSecurityAtlassianCrowdVerifyConnection tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateSecurityAtlassianCrowdVerifyConnectionHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "*/*"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/security/atlassian-crowd/verify-connection", args, []string{}, contentType, "CreateSecurityAtlassianCrowdVerifyConnection")
}
