// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateBlobstoresFile tool
const CreateBlobstoresFileInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"name\": {\n          \"minLength\": 1,\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        },\n        \"path\": {\n          \"description\": \"An absolute path or a path relative to \\u003cdata-directory\\u003e/blobs\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"softQuota\": {\n          \"description\": \"Settings to control the soft quota.\",\n          \"properties\": {\n            \"limit\": {\n              \"description\": \"The limit in MB.\",\n              \"format\": \"int64\",\n              \"minimum\": 0,\n              \"type\": \"integer\"\n            },\n            \"type\": {\n              \"description\": \"The type to use such as spaceRemainingQuota, or spaceUsedQuotaspaceUsedQuota\",\n              \"minLength\": 1,\n              \"type\": \"string\"\n            }\n          },\n          \"required\": [\n            \"type\"\n          ],\n          \"type\": \"object\"\n        },\n        \"softQuotaAttributes\": {\n          \"properties\": {\n            \"attributes\": {\n              \"additionalProperties\": {\n                \"additionalProperties\": {\n                  \"type\": \"object\"\n                },\n                \"type\": \"object\"\n              },\n              \"type\": \"object\"\n            },\n            \"name\": {\n              \"type\": \"string\"\n            },\n            \"type\": {\n              \"type\": \"string\"\n            },\n            \"writable\": {\n              \"type\": \"boolean\"\n            }\n          },\n          \"type\": \"object\"\n        }\n      },\n      \"required\": [\n        \"name\",\n        \"path\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewCreateBlobstoresFileMCPTool creates the MCP Tool instance for CreateBlobstoresFile
func NewCreateBlobstoresFileMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateBlobstoresFile",
		"Create a file blob store",
		[]byte(CreateBlobstoresFileInputSchema),
	)
}

// CreateBlobstoresFileHandler is the handler function for the CreateBlobstoresFile tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateBlobstoresFileHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/blobstores/file", args, []string{}, contentType, "CreateBlobstoresFile")
}
