// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateRepositoriesHealthCheck tool
const CreateRepositoriesHealthCheckInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"description\": \"Name of the repository to enable Repository Health Check for\",\n      \"type\": \"string\"\n    },\n    \"source\": {\n      \"description\": \"Source of the request (e.g. 'detect' for Malicious Packages Detect module)\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateRepositoriesHealthCheckMCPTool creates the MCP Tool instance for CreateRepositoriesHealthCheck
func NewCreateRepositoriesHealthCheckMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateRepositoriesHealthCheck",
		"Enable repository health check. Proxy repositories only.",
		[]byte(CreateRepositoriesHealthCheckInputSchema),
	)
}

// CreateRepositoriesHealthCheckHandler is the handler function for the CreateRepositoriesHealthCheck tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateRepositoriesHealthCheckHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/repositories/{repositoryName}/health-check", args, []string{"repositoryName"}, contentType, "CreateRepositoriesHealthCheck")
}
