// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the CreateRoutingRules tool
const CreateRoutingRulesInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"A routing rule configuration\",\n      \"properties\": {\n        \"description\": {\n          \"type\": \"string\"\n        },\n        \"matchers\": {\n          \"description\": \"Regular expressions used to identify request paths that are allowed or blocked (depending on mode)\",\n          \"items\": {\n            \"description\": \"Regular expressions used to identify request paths that are allowed or blocked (depending on mode)\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\"\n        },\n        \"mode\": {\n          \"description\": \"Determines what should be done with requests when their path matches any of the matchers\",\n          \"enum\": [\n            \"ALLOW\",\n            \"BLOCK\"\n          ],\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"pattern\": \"^[a-zA-Z0-9\\\\-]{1}[a-zA-Z0-9_\\\\-\\\\.]*$\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewCreateRoutingRulesMCPTool creates the MCP Tool instance for CreateRoutingRules
func NewCreateRoutingRulesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"CreateRoutingRules",
		"Create a single routing rule",
		[]byte(CreateRoutingRulesInputSchema),
	)
}

// CreateRoutingRulesHandler is the handler function for the CreateRoutingRules tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func CreateRoutingRulesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "POST", "/service/rest/v1/routing-rules", args, []string{}, contentType, "CreateRoutingRules")
}
