// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRoutingRules tool
const DeleteRoutingRulesInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"The name of the routing rule to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRoutingRulesMCPTool creates the MCP Tool instance for DeleteRoutingRules
func NewDeleteRoutingRulesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRoutingRules",
		"Delete a single routing rule",
		[]byte(DeleteRoutingRulesInputSchema),
	)
}

// DeleteRoutingRulesHandler is the handler function for the DeleteRoutingRules tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRoutingRulesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/routing-rules/{name}", args, []string{"name"}, contentType, "DeleteRoutingRules")
}
