// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityRoles tool
const DeleteSecurityRolesInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"The id of the role to delete\",\n      \"minLength\": 1,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSecurityRolesMCPTool creates the MCP Tool instance for DeleteSecurityRoles
func NewDeleteSecurityRolesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityRoles",
		"Delete role",
		[]byte(DeleteSecurityRolesInputSchema),
	)
}

// DeleteSecurityRolesHandler is the handler function for the DeleteSecurityRoles tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityRolesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/roles/{id}", args, []string{"id"}, contentType, "DeleteSecurityRoles")
}
