// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteInternalCleanupPolicies tool
const DeleteInternalCleanupPoliciesInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteInternalCleanupPoliciesMCPTool creates the MCP Tool instance for DeleteInternalCleanupPolicies
func NewDeleteInternalCleanupPoliciesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteInternalCleanupPolicies",
		"",
		[]byte(DeleteInternalCleanupPoliciesInputSchema),
	)
}

// DeleteInternalCleanupPoliciesHandler is the handler function for the DeleteInternalCleanupPolicies tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteInternalCleanupPoliciesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/internal/cleanup-policies/{name}", args, []string{"name"}, contentType, "DeleteInternalCleanupPolicies")
}
