// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSystemLicense tool
const DeleteSystemLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteSystemLicenseMCPTool creates the MCP Tool instance for DeleteSystemLicense
func NewDeleteSystemLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSystemLicense",
		"Uninstall license if present.",
		[]byte(DeleteSystemLicenseInputSchema),
	)
}

// DeleteSystemLicenseHandler is the handler function for the DeleteSystemLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSystemLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/system/license", args, []string{}, contentType, "DeleteSystemLicense")
}
