// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteBlobstores tool
const DeleteBlobstoresInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"The name of the blob store to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteBlobstoresMCPTool creates the MCP Tool instance for DeleteBlobstores
func NewDeleteBlobstoresMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteBlobstores",
		"Delete a blob store by name",
		[]byte(DeleteBlobstoresInputSchema),
	)
}

// DeleteBlobstoresHandler is the handler function for the DeleteBlobstores tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteBlobstoresHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/blobstores/{name}", args, []string{"name"}, contentType, "DeleteBlobstores")
}
