// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteComponents tool
const DeleteComponentsInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"ID of the component to delete\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteComponentsMCPTool creates the MCP Tool instance for DeleteComponents
func NewDeleteComponentsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteComponents",
		"Delete a single component",
		[]byte(DeleteComponentsInputSchema),
	)
}

// DeleteComponentsHandler is the handler function for the DeleteComponents tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteComponentsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/components/{id}", args, []string{"id"}, contentType, "DeleteComponents")
}
