// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRepositoriesBrowse tool
const DeleteRepositoriesBrowseInputSchema = "{\n  \"properties\": {\n    \"path\": {\n      \"description\": \"Folder path to delete (URL-encoded)\",\n      \"type\": \"string\"\n    },\n    \"repositoryName\": {\n      \"description\": \"Repository name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"path\",\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteRepositoriesBrowseMCPTool creates the MCP Tool instance for DeleteRepositoriesBrowse
func NewDeleteRepositoriesBrowseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRepositoriesBrowse",
		"Delete a folder and all its contents",
		[]byte(DeleteRepositoriesBrowseInputSchema),
	)
}

// DeleteRepositoriesBrowseHandler is the handler function for the DeleteRepositoriesBrowse tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRepositoriesBrowseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/repositories/{repositoryName}/browse", args, []string{"repositoryName"}, contentType, "DeleteRepositoriesBrowse")
}
