// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteEmail tool
const DeleteEmailInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteEmailMCPTool creates the MCP Tool instance for DeleteEmail
func NewDeleteEmailMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteEmail",
		"Disable and clear the email configuration",
		[]byte(DeleteEmailInputSchema),
	)
}

// DeleteEmailHandler is the handler function for the DeleteEmail tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteEmailHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/email", args, []string{}, contentType, "DeleteEmail")
}
