// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityContentSelectors tool
const DeleteSecurityContentSelectorsInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSecurityContentSelectorsMCPTool creates the MCP Tool instance for DeleteSecurityContentSelectors
func NewDeleteSecurityContentSelectorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityContentSelectors",
		"Delete a content selector",
		[]byte(DeleteSecurityContentSelectorsInputSchema),
	)
}

// DeleteSecurityContentSelectorsHandler is the handler function for the DeleteSecurityContentSelectors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityContentSelectorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/content-selectors/{name}", args, []string{"name"}, contentType, "DeleteSecurityContentSelectors")
}
