// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteRecoveryMode tool
const DeleteRecoveryModeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteRecoveryModeMCPTool creates the MCP Tool instance for DeleteRecoveryMode
func NewDeleteRecoveryModeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteRecoveryMode",
		"Disables recovery mode",
		[]byte(DeleteRecoveryModeInputSchema),
	)
}

// DeleteRecoveryModeHandler is the handler function for the DeleteRecoveryMode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteRecoveryModeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/recovery-mode", args, []string{}, contentType, "DeleteRecoveryMode")
}
