// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityLdapCache tool
const DeleteSecurityLdapCacheInputSchema = "{\n  \"type\": \"object\"\n}"

// NewDeleteSecurityLdapCacheMCPTool creates the MCP Tool instance for DeleteSecurityLdapCache
func NewDeleteSecurityLdapCacheMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityLdapCache",
		"",
		[]byte(DeleteSecurityLdapCacheInputSchema),
	)
}

// DeleteSecurityLdapCacheHandler is the handler function for the DeleteSecurityLdapCache tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityLdapCacheHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/ldap/cache", args, []string{}, contentType, "DeleteSecurityLdapCache")
}
