// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the DeleteSecurityUsers tool
const DeleteSecurityUsersInputSchema = "{\n  \"properties\": {\n    \"realm\": {\n      \"description\": \"The realm the request should apply to.\",\n      \"type\": \"string\"\n    },\n    \"userId\": {\n      \"description\": \"The userid the request should apply to.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"userId\"\n  ],\n  \"type\": \"object\"\n}"

// NewDeleteSecurityUsersMCPTool creates the MCP Tool instance for DeleteSecurityUsers
func NewDeleteSecurityUsersMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"DeleteSecurityUsers",
		"Delete a user.",
		[]byte(DeleteSecurityUsersInputSchema),
	)
}

// DeleteSecurityUsersHandler is the handler function for the DeleteSecurityUsers tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func DeleteSecurityUsersHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "DELETE", "/service/rest/v1/security/users/{userId}", args, []string{"userId"}, contentType, "DeleteSecurityUsers")
}
