// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetAssets tool
const GetAssetsInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the asset to get\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetAssetsMCPTool creates the MCP Tool instance for GetAssets
func NewGetAssetsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetAssets",
		"Get a single asset",
		[]byte(GetAssetsInputSchema),
	)
}

// GetAssetsHandler is the handler function for the GetAssets tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetAssetsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/assets/{id}", args, []string{"id"}, contentType, "GetAssets")
}
