// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetBlobstoresQuotaStatus tool
const GetBlobstoresQuotaStatusInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetBlobstoresQuotaStatus tool (Status: 0, Content-Type: application/json)
const GetBlobstoresQuotaStatusResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: object):\n  - **blobStoreName** (Type: string):\n      - Min Length: 1\n  - **isViolation** (Type: boolean):\n  - **message** (Type: string):\n      - Min Length: 1\n"

// NewGetBlobstoresQuotaStatusMCPTool creates the MCP Tool instance for GetBlobstoresQuotaStatus
func NewGetBlobstoresQuotaStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetBlobstoresQuotaStatus",
		"Get quota status for a given blob store",
		[]byte(GetBlobstoresQuotaStatusInputSchema),
	)
}

// GetBlobstoresQuotaStatusHandler is the handler function for the GetBlobstoresQuotaStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetBlobstoresQuotaStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/blobstores/{name}/quota-status", args, []string{"name"}, contentType, "GetBlobstoresQuotaStatus")
}
