// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetComponents tool
const GetComponentsInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"ID of the component to retrieve\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetComponentsMCPTool creates the MCP Tool instance for GetComponents
func NewGetComponentsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetComponents",
		"Get a single component",
		[]byte(GetComponentsInputSchema),
	)
}

// GetComponentsHandler is the handler function for the GetComponents tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetComponentsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/components/{id}", args, []string{"id"}, contentType, "GetComponents")
}
