// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetRepositoriesAnsiblegalaxyGroup tool
const GetRepositoriesAnsiblegalaxyGroupInputSchema = "{\n  \"properties\": {\n    \"repositoryName\": {\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repositoryName\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetRepositoriesAnsiblegalaxyGroup tool (Status: 200, Content-Type: application/json)
const GetRepositoriesAnsiblegalaxyGroupResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n## Response Structure\n\n- Ansible Galaxy group repository configuration (Type: object):\n  - **format**: Component format held in this repository (Type: string):\n      - Min Length: 1\n      - Example: 'ansiblegalaxy'\n  - **group** (Type: object):\n    - **memberNames**: Member repositories' names (Type: array):\n        - Min Items: 1\n      - **Items**: Member repositories' names (Type: string):\n  - **name**: A unique identifier for this repository (Type: string):\n      - Min Length: 1\n      - Pattern: '^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$'\n      - Example: 'internal'\n  - **online**: Whether this repository accepts incoming requests (Type: boolean):\n      - Example: 'true'\n  - **storage** (Type: object):\n    - **blobStoreName**: Blob store used to store repository contents (Type: string):\n        - Min Length: 1\n        - Example: 'default'\n    - **strictContentTypeValidation**: Whether to validate uploaded content's MIME type appropriate for the repository format (Type: boolean):\n        - Example: 'true'\n  - **type**: Controls if deployments of and updates to artifacts are allowed (Type: string):\n      - Min Length: 1\n      - Example: 'group'\n  - **url**: URL to the repository (Type: string):\n      - Example: 'http://localhost:8081/repository/ansiblegalaxy-example'\n"

// NewGetRepositoriesAnsiblegalaxyGroupMCPTool creates the MCP Tool instance for GetRepositoriesAnsiblegalaxyGroup
func NewGetRepositoriesAnsiblegalaxyGroupMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetRepositoriesAnsiblegalaxyGroup",
		"Get repository",
		[]byte(GetRepositoriesAnsiblegalaxyGroupInputSchema),
	)
}

// GetRepositoriesAnsiblegalaxyGroupHandler is the handler function for the GetRepositoriesAnsiblegalaxyGroup tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetRepositoriesAnsiblegalaxyGroupHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/repositories/ansiblegalaxy/group/{repositoryName}", args, []string{"repositoryName"}, contentType, "GetRepositoriesAnsiblegalaxyGroup")
}
