// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSecurityPrivileges tool
const GetSecurityPrivilegesInputSchema = "{\n  \"properties\": {\n    \"privilegeName\": {\n      \"description\": \"The name of the privilege to retrieve.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"privilegeName\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetSecurityPrivilegesMCPTool creates the MCP Tool instance for GetSecurityPrivileges
func NewGetSecurityPrivilegesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSecurityPrivileges",
		"Retrieve a privilege by name.",
		[]byte(GetSecurityPrivilegesInputSchema),
	)
}

// GetSecurityPrivilegesHandler is the handler function for the GetSecurityPrivileges tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSecurityPrivilegesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/privileges/{privilegeName}", args, []string{"privilegeName"}, contentType, "GetSecurityPrivileges")
}
