// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSecurityContentSelectors tool
const GetSecurityContentSelectorsInputSchema = "{\n  \"properties\": {\n    \"name\": {\n      \"description\": \"The content selector name\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"name\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the GetSecurityContentSelectors tool (Status: 200, Content-Type: application/json)
const GetSecurityContentSelectorsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> successful operation\n\n## Response Structure\n\n- Structure (Type: object):\n  - **description**: A human-readable description (Type: string):\n  - **expression**: The expression used to identify content (Type: string):\n      - Example: 'format == \"maven2\" and path =^ \"/org/sonatype/nexus\"'\n  - **name**: The content selector name cannot be changed after creation (Type: string):\n  - **type**: The type of content selector the backend is using (Type: string):\n"

// NewGetSecurityContentSelectorsMCPTool creates the MCP Tool instance for GetSecurityContentSelectors
func NewGetSecurityContentSelectorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSecurityContentSelectors",
		"Get a content selector by name",
		[]byte(GetSecurityContentSelectorsInputSchema),
	)
}

// GetSecurityContentSelectorsHandler is the handler function for the GetSecurityContentSelectors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSecurityContentSelectorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/content-selectors/{name}", args, []string{"name"}, contentType, "GetSecurityContentSelectors")
}
