// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetSecurityRoles tool
const GetSecurityRolesInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"The id of the role to get\",\n      \"minLength\": 1,\n      \"type\": \"string\"\n    },\n    \"source\": {\n      \"default\": \"default\",\n      \"description\": \"The id of the user source to filter the roles by. Available sources can be fetched using the 'User Sources' endpoint.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetSecurityRolesMCPTool creates the MCP Tool instance for GetSecurityRoles
func NewGetSecurityRolesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetSecurityRoles",
		"Get role",
		[]byte(GetSecurityRolesInputSchema),
	)
}

// GetSecurityRolesHandler is the handler function for the GetSecurityRoles tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetSecurityRolesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/roles/{id}", args, []string{"id"}, contentType, "GetSecurityRoles")
}
