// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the GetTasks tool
const GetTasksInputSchema = "{\n  \"properties\": {\n    \"id\": {\n      \"description\": \"Id of the task to get\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewGetTasksMCPTool creates the MCP Tool instance for GetTasks
func NewGetTasksMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"GetTasks",
		"Get a single task by id",
		[]byte(GetTasksInputSchema),
	)
}

// GetTasksHandler is the handler function for the GetTasks tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func GetTasksHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/tasks/{id}", args, []string{"id"}, contentType, "GetTasks")
}
