// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListConfiguration tool
const ListConfigurationInputSchema = "{\n  \"properties\": {\n    \"X-Nexus-Migration-Protocol-Version\": {\n      \"description\": \"Migration protocol version (must be '1')\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"X-Nexus-Migration-Protocol-Version\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the ListConfiguration tool (Status: 200, Content-Type: application/json)
const ListConfigurationResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful Operation\n\n## Response Structure\n\n- Structure (Type: object):\n  - **configurationXOs** (Type: array):\n    - **Items** (Type: object):\n      - **configurationTypeId** (Type: string):\n"

// Response Template for the ListConfiguration tool (Status: 400, Content-Type: application/json)
const ListConfigurationResponseTemplate_B = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 400\n\n**Content-Type:** application/json\n\n> Missing or invalid protocol version\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the ListConfiguration tool (Status: 401, Content-Type: application/json)
const ListConfigurationResponseTemplate_C = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 401\n\n**Content-Type:** application/json\n\n> Authentication required\n\n## Response Structure\n\n- Structure (Type: string):\n"

// Response Template for the ListConfiguration tool (Status: 403, Content-Type: application/json)
const ListConfigurationResponseTemplate_D = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 403\n\n**Content-Type:** application/json\n\n> Insufficient permissions\n\n## Response Structure\n\n- Structure (Type: string):\n"

// NewListConfigurationMCPTool creates the MCP Tool instance for ListConfiguration
func NewListConfigurationMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListConfiguration",
		"Export instance configuration",
		[]byte(ListConfigurationInputSchema),
	)
}

// ListConfigurationHandler is the handler function for the ListConfiguration tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListConfigurationHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/configuration", args, []string{}, contentType, "ListConfiguration")
}
