// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListStatusWritable tool
const ListStatusWritableInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListStatusWritableMCPTool creates the MCP Tool instance for ListStatusWritable
func NewListStatusWritableMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListStatusWritable",
		"Health check endpoint that validates server can respond to read and write requests",
		[]byte(ListStatusWritableInputSchema),
	)
}

// ListStatusWritableHandler is the handler function for the ListStatusWritable tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListStatusWritableHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/status/writable", args, []string{}, contentType, "ListStatusWritable")
}
