// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityAtlassianCrowd tool
const ListSecurityAtlassianCrowdInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSecurityAtlassianCrowdMCPTool creates the MCP Tool instance for ListSecurityAtlassianCrowd
func NewListSecurityAtlassianCrowdMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityAtlassianCrowd",
		"Retrieve Atlassian Crowd settings configured in Nexus Repository Manager",
		[]byte(ListSecurityAtlassianCrowdInputSchema),
	)
}

// ListSecurityAtlassianCrowdHandler is the handler function for the ListSecurityAtlassianCrowd tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityAtlassianCrowdHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/atlassian-crowd", args, []string{}, contentType, "ListSecurityAtlassianCrowd")
}
