// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListIqAudit tool
const ListIqAuditInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListIqAudit tool (Status: 200, Content-Type: application/json)
const ListIqAuditResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Successful Operation\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **enabled**: is audit enabled (Type: boolean):\n    - **enabledQuarantine**: is quarantine enabled (Type: boolean):\n    - **repositoryName**: repository name (Type: string):\n"

// NewListIqAuditMCPTool creates the MCP Tool instance for ListIqAudit
func NewListIqAuditMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListIqAudit",
		"List repositories audit statuses.",
		[]byte(ListIqAuditInputSchema),
	)
}

// ListIqAuditHandler is the handler function for the ListIqAudit tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListIqAuditHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/iq/audit", args, []string{}, contentType, "ListIqAudit")
}
