// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSearchSuggest tool
const ListSearchSuggestInputSchema = "{\n  \"properties\": {\n    \"format\": {\n      \"description\": \"Filter by format (e.g., maven2, npm, pypi)\",\n      \"type\": \"string\"\n    },\n    \"limit\": {\n      \"description\": \"Maximum number of suggestions (default: 10, max: 20)\",\n      \"format\": \"int32\",\n      \"type\": \"integer\"\n    },\n    \"q\": {\n      \"description\": \"Search query (minimum 2 characters)\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"q\"\n  ],\n  \"type\": \"object\"\n}"

// Response Template for the ListSearchSuggest tool (Status: 200, Content-Type: application/json)
const ListSearchSuggestResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Suggestions returned successfully\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **format** (Type: string):\n    - **group** (Type: string):\n    - **id** (Type: string):\n    - **name** (Type: string):\n    - **repository** (Type: string):\n    - **version** (Type: string):\n"

// NewListSearchSuggestMCPTool creates the MCP Tool instance for ListSearchSuggest
func NewListSearchSuggestMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSearchSuggest",
		"Get search suggestions for autocomplete - Returns lightweight component suggestions matching the query. Optimized for fast typeahead with minimal response payload.",
		[]byte(ListSearchSuggestInputSchema),
	)
}

// ListSearchSuggestHandler is the handler function for the ListSearchSuggest tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSearchSuggestHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/search/suggest", args, []string{}, contentType, "ListSearchSuggest")
}
