// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListEmail tool
const ListEmailInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListEmailMCPTool creates the MCP Tool instance for ListEmail
func NewListEmailMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListEmail",
		"Retrieve the current email configuration",
		[]byte(ListEmailInputSchema),
	)
}

// ListEmailHandler is the handler function for the ListEmail tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListEmailHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/email", args, []string{}, contentType, "ListEmail")
}
