// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityUserSources tool
const ListSecurityUserSourcesInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSecurityUserSourcesMCPTool creates the MCP Tool instance for ListSecurityUserSources
func NewListSecurityUserSourcesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityUserSources",
		"Retrieve a list of the available user sources.",
		[]byte(ListSecurityUserSourcesInputSchema),
	)
}

// ListSecurityUserSourcesHandler is the handler function for the ListSecurityUserSources tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityUserSourcesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/user-sources", args, []string{}, contentType, "ListSecurityUserSources")
}
