// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListStatus tool
const ListStatusInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListStatusMCPTool creates the MCP Tool instance for ListStatus
func NewListStatusMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListStatus",
		"Health check endpoint that validates server can respond to read requests",
		[]byte(ListStatusInputSchema),
	)
}

// ListStatusHandler is the handler function for the ListStatus tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListStatusHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/status", args, []string{}, contentType, "ListStatus")
}
