// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListRepositorySettings tool
const ListRepositorySettingsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListRepositorySettings tool (Status: 200, Content-Type: application/json)
const ListRepositorySettingsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> Repositories list returned\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **format**: Component format held in this repository (Type: string):\n        - Min Length: 1\n        - Example: 'npm'\n    - **name**: A unique identifier for this repository (Type: string):\n        - Min Length: 1\n        - Pattern: '^[a-zA-Z0-9\\-]{1}[a-zA-Z0-9_\\-\\.]*$'\n        - Example: 'internal'\n    - **online**: Whether this repository accepts incoming requests (Type: boolean):\n        - Example: 'true'\n    - **type**: Controls if deployments of and updates to artifacts are allowed (Type: string):\n        - Min Length: 1\n        - Example: 'hosted'\n    - **url**: URL to the repository (Type: string):\n"

// NewListRepositorySettingsMCPTool creates the MCP Tool instance for ListRepositorySettings
func NewListRepositorySettingsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListRepositorySettings",
		"List repositories",
		[]byte(ListRepositorySettingsInputSchema),
	)
}

// ListRepositorySettingsHandler is the handler function for the ListRepositorySettings tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListRepositorySettingsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/repositorySettings", args, []string{}, contentType, "ListRepositorySettings")
}
