// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListRepositories tool
const ListRepositoriesInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListRepositories tool (Status: 0, Content-Type: application/json)
const ListRepositoriesResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **attributes** (Type: object):\n      - **Additional Properties**:\n        - **property value** (Type: object):\n    - **format** (Type: string):\n    - **name** (Type: string):\n    - **online**: Whether this repository accepts incoming requests (Type: boolean):\n        - Example: 'true'\n    - **size**: Size of the repository in bytes (Type: integer, int64):\n    - **type** (Type: string):\n    - **url** (Type: string):\n"

// NewListRepositoriesMCPTool creates the MCP Tool instance for ListRepositories
func NewListRepositoriesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListRepositories",
		"List repositories",
		[]byte(ListRepositoriesInputSchema),
	)
}

// ListRepositoriesHandler is the handler function for the ListRepositories tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListRepositoriesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/repositories", args, []string{}, contentType, "ListRepositories")
}
