// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListAssets tool
const ListAssetsInputSchema = "{\n  \"properties\": {\n    \"continuationToken\": {\n      \"description\": \"A token returned by a prior request. If present, the next page of results are returned\",\n      \"type\": \"string\"\n    },\n    \"repository\": {\n      \"description\": \"Repository from which you would like to retrieve assets.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"repository\"\n  ],\n  \"type\": \"object\"\n}"

// NewListAssetsMCPTool creates the MCP Tool instance for ListAssets
func NewListAssetsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListAssets",
		"List assets",
		[]byte(ListAssetsInputSchema),
	)
}

// ListAssetsHandler is the handler function for the ListAssets tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListAssetsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/assets", args, []string{}, contentType, "ListAssets")
}
