// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListPlan tool
const ListPlanInputSchema = "{\n  \"properties\": {\n    \"continuationToken\": {\n      \"description\": \"A token returned by a prior request. If present, the next page of results are returned\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewListPlanMCPTool creates the MCP Tool instance for ListPlan
func NewListPlanMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListPlan",
		"Get list of currently available plans",
		[]byte(ListPlanInputSchema),
	)
}

// ListPlanHandler is the handler function for the ListPlan tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListPlanHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/plan", args, []string{}, contentType, "ListPlan")
}
