// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListFormatsUploadSpecs tool
const ListFormatsUploadSpecsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListFormatsUploadSpecs tool (Status: 0, Content-Type: application/json)
const ListFormatsUploadSpecsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **assetFields** (Type: array):\n      - **Items** (Type: object):\n        - **description** (Type: string):\n        - **group** (Type: string):\n        - **groupHelpText** (Type: string):\n        - **name** (Type: string):\n        - **optional** (Type: boolean):\n        - **options** (Type: object):\n          - **Additional Properties**:\n            - **property value** (Type: string):\n        - **type** (Type: string):\n    - **componentFields** (Type: array):\n      - **[cyclic reference]**\n    - **format** (Type: string):\n    - **multipleUpload** (Type: boolean):\n"

// NewListFormatsUploadSpecsMCPTool creates the MCP Tool instance for ListFormatsUploadSpecs
func NewListFormatsUploadSpecsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListFormatsUploadSpecs",
		"Get upload field requirements for each supported format",
		[]byte(ListFormatsUploadSpecsInputSchema),
	)
}

// ListFormatsUploadSpecsHandler is the handler function for the ListFormatsUploadSpecs tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListFormatsUploadSpecsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/formats/upload-specs", args, []string{}, contentType, "ListFormatsUploadSpecs")
}
