// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSystemLicense tool
const ListSystemLicenseInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListSystemLicense tool (Status: 0, Content-Type: application/json)
const ListSystemLicenseResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** default\n\n**Content-Type:** application/json\n\n> default response\n\n## Response Structure\n\n- Structure (Type: object):\n  - **contactCompany** (Type: string):\n  - **contactEmail** (Type: string):\n  - **contactName** (Type: string):\n  - **effectiveDate** (Type: string, date-time):\n  - **expirationDate** (Type: string, date-time):\n  - **features** (Type: string):\n  - **fingerprint** (Type: string):\n  - **licenseType** (Type: string):\n  - **licensedUsers** (Type: string):\n  - **maxRepoComponents** (Type: integer, int64):\n  - **maxRepoRequests** (Type: integer, int64):\n"

// NewListSystemLicenseMCPTool creates the MCP Tool instance for ListSystemLicense
func NewListSystemLicenseMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSystemLicense",
		"Get the current license status.",
		[]byte(ListSystemLicenseInputSchema),
	)
}

// ListSystemLicenseHandler is the handler function for the ListSystemLicense tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSystemLicenseHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/system/license", args, []string{}, contentType, "ListSystemLicense")
}
