// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListRoutingRules tool
const ListRoutingRulesInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListRoutingRulesMCPTool creates the MCP Tool instance for ListRoutingRules
func NewListRoutingRulesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListRoutingRules",
		"List routing rules",
		[]byte(ListRoutingRulesInputSchema),
	)
}

// ListRoutingRulesHandler is the handler function for the ListRoutingRules tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListRoutingRulesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/routing-rules", args, []string{}, contentType, "ListRoutingRules")
}
