// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityAnonymous tool
const ListSecurityAnonymousInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSecurityAnonymousMCPTool creates the MCP Tool instance for ListSecurityAnonymous
func NewListSecurityAnonymousMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityAnonymous",
		"Get Anonymous Access settings",
		[]byte(ListSecurityAnonymousInputSchema),
	)
}

// ListSecurityAnonymousHandler is the handler function for the ListSecurityAnonymous tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityAnonymousHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/anonymous", args, []string{}, contentType, "ListSecurityAnonymous")
}
