// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityRoles tool
const ListSecurityRolesInputSchema = "{\n  \"properties\": {\n    \"source\": {\n      \"description\": \"The id of the user source to filter the roles by, if supplied. Otherwise roles from all user sources will be returned.\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewListSecurityRolesMCPTool creates the MCP Tool instance for ListSecurityRoles
func NewListSecurityRolesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityRoles",
		"List roles",
		[]byte(ListSecurityRolesInputSchema),
	)
}

// ListSecurityRolesHandler is the handler function for the ListSecurityRoles tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityRolesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/roles", args, []string{}, contentType, "ListSecurityRoles")
}
