// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityPrivileges tool
const ListSecurityPrivilegesInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSecurityPrivilegesMCPTool creates the MCP Tool instance for ListSecurityPrivileges
func NewListSecurityPrivilegesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityPrivileges",
		"Retrieve a list of privileges.",
		[]byte(ListSecurityPrivilegesInputSchema),
	)
}

// ListSecurityPrivilegesHandler is the handler function for the ListSecurityPrivileges tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityPrivilegesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/privileges", args, []string{}, contentType, "ListSecurityPrivileges")
}
