// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSystemNode tool
const ListSystemNodeInputSchema = "{\n  \"type\": \"object\"\n}"

// NewListSystemNodeMCPTool creates the MCP Tool instance for ListSystemNode
func NewListSystemNodeMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSystemNode",
		"Get information about this node",
		[]byte(ListSystemNodeInputSchema),
	)
}

// ListSystemNodeHandler is the handler function for the ListSystemNode tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSystemNodeHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/system/node", args, []string{}, contentType, "ListSystemNode")
}
