// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the ListSecurityContentSelectors tool
const ListSecurityContentSelectorsInputSchema = "{\n  \"type\": \"object\"\n}"

// Response Template for the ListSecurityContentSelectors tool (Status: 200, Content-Type: application/json)
const ListSecurityContentSelectorsResponseTemplate_A = "# API Response Information\n\nBelow is the response template for this API endpoint.\n\nThe template shows a possible response, including its status code and content type, to help you understand and generate correct outputs.\n\n**Status Code:** 200\n\n**Content-Type:** application/json\n\n> successful operation\n\n## Response Structure\n\n- Structure (Type: array):\n  - **Items** (Type: object):\n    - **description**: A human-readable description (Type: string):\n    - **expression**: The expression used to identify content (Type: string):\n        - Example: 'format == \"maven2\" and path =^ \"/org/sonatype/nexus\"'\n    - **name**: The content selector name cannot be changed after creation (Type: string):\n    - **type**: The type of content selector the backend is using (Type: string):\n"

// NewListSecurityContentSelectorsMCPTool creates the MCP Tool instance for ListSecurityContentSelectors
func NewListSecurityContentSelectorsMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"ListSecurityContentSelectors",
		"List content selectors",
		[]byte(ListSecurityContentSelectorsInputSchema),
	)
}

// ListSecurityContentSelectorsHandler is the handler function for the ListSecurityContentSelectors tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func ListSecurityContentSelectorsHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := ""
	return mcputils.ForwardAndParseResponse(ctx, upstream, "GET", "/service/rest/v1/security/content-selectors", args, []string{}, contentType, "ListSecurityContentSelectors")
}
