// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityUsersChangePassword tool
const UpdateSecurityUsersChangePasswordInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The new password to use.\",\n      \"type\": \"string\"\n    },\n    \"userId\": {\n      \"description\": \"The userid the request should apply to.\",\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"userId\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateSecurityUsersChangePasswordMCPTool creates the MCP Tool instance for UpdateSecurityUsersChangePassword
func NewUpdateSecurityUsersChangePasswordMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityUsersChangePassword",
		"Change a user's password.",
		[]byte(UpdateSecurityUsersChangePasswordInputSchema),
	)
}

// UpdateSecurityUsersChangePasswordHandler is the handler function for the UpdateSecurityUsersChangePassword tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityUsersChangePasswordHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "text/plain"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/users/{userId}/change-password", args, []string{"userId"}, contentType, "UpdateSecurityUsersChangePassword")
}
