// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateLifecycleBounce tool
const UpdateLifecycleBounceInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The phase to bounce\",\n      \"type\": \"string\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateLifecycleBounceMCPTool creates the MCP Tool instance for UpdateLifecycleBounce
func NewUpdateLifecycleBounceMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateLifecycleBounce",
		"Bounce lifecycle phase - Re-runs all phases from the given phase to the current phase",
		[]byte(UpdateLifecycleBounceInputSchema),
	)
}

// UpdateLifecycleBounceHandler is the handler function for the UpdateLifecycleBounce tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateLifecycleBounceHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "text/plain"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/lifecycle/bounce", args, []string{}, contentType, "UpdateLifecycleBounce")
}
