// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateIqAudit tool
const UpdateIqAuditInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"enabled\": {\n          \"description\": \"is audit enabled\",\n          \"type\": \"boolean\"\n        },\n        \"enabledQuarantine\": {\n          \"description\": \"is quarantine enabled\",\n          \"type\": \"boolean\"\n        },\n        \"repositoryName\": {\n          \"description\": \"repository name\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"enabledQuarantine\",\n        \"repositoryName\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateIqAuditMCPTool creates the MCP Tool instance for UpdateIqAudit
func NewUpdateIqAuditMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateIqAudit",
		"Manage audit",
		[]byte(UpdateIqAuditInputSchema),
	)
}

// UpdateIqAuditHandler is the handler function for the UpdateIqAudit tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateIqAuditHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/iq/audit", args, []string{}, contentType, "UpdateIqAudit")
}
