// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateApikeysEncryptionReEncrypt tool
const UpdateApikeysEncryptionReEncryptInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"algorithmForDecryption\": {\n          \"description\": \"Optional - The algorithm to be used to decrypt the principals\",\n          \"type\": \"string\"\n        },\n        \"iterationsForDecryption\": {\n          \"description\": \"Optional - The iterations to be used to decrypt the principals\",\n          \"format\": \"int32\",\n          \"type\": \"integer\"\n        },\n        \"notifyEmail\": {\n          \"description\": \"Optional - Email to notify when task finishes\",\n          \"type\": \"string\"\n        }\n      },\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateApikeysEncryptionReEncryptMCPTool creates the MCP Tool instance for UpdateApikeysEncryptionReEncrypt
func NewUpdateApikeysEncryptionReEncryptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateApikeysEncryptionReEncrypt",
		"Re-encrypt api keys principals using the specified configuration - Ensure all nodes have access to the key, and they use the same key",
		[]byte(UpdateApikeysEncryptionReEncryptInputSchema),
	)
}

// UpdateApikeysEncryptionReEncryptHandler is the handler function for the UpdateApikeysEncryptionReEncrypt tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateApikeysEncryptionReEncryptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/apikeys/encryption/re-encrypt", args, []string{}, contentType, "UpdateApikeysEncryptionReEncrypt")
}
