// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityRoles tool
const UpdateSecurityRolesInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"A role configuration\",\n      \"properties\": {\n        \"description\": {\n          \"description\": \"The description of this role.\",\n          \"type\": \"string\"\n        },\n        \"id\": {\n          \"description\": \"The id of the role.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the role.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"privileges\": {\n          \"description\": \"The list of privileges assigned to this role.\",\n          \"items\": {\n            \"description\": \"The list of privileges assigned to this role.\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        },\n        \"roles\": {\n          \"description\": \"The list of roles assigned to this role.\",\n          \"items\": {\n            \"description\": \"The list of roles assigned to this role.\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        }\n      },\n      \"required\": [\n        \"id\",\n        \"name\"\n      ],\n      \"type\": \"object\"\n    },\n    \"id\": {\n      \"description\": \"The id of the role to update\",\n      \"minLength\": 1,\n      \"type\": \"string\"\n    }\n  },\n  \"required\": [\n    \"body\",\n    \"id\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateSecurityRolesMCPTool creates the MCP Tool instance for UpdateSecurityRoles
func NewUpdateSecurityRolesMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityRoles",
		"Update role",
		[]byte(UpdateSecurityRolesInputSchema),
	)
}

// UpdateSecurityRolesHandler is the handler function for the UpdateSecurityRoles tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityRolesHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/roles/{id}", args, []string{"id"}, contentType, "UpdateSecurityRoles")
}
