// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityRealmsActive tool
const UpdateSecurityRealmsActiveInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"description\": \"The realm IDs\",\n      \"items\": {\n        \"type\": \"string\"\n      },\n      \"type\": \"array\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateSecurityRealmsActiveMCPTool creates the MCP Tool instance for UpdateSecurityRealmsActive
func NewUpdateSecurityRealmsActiveMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityRealmsActive",
		"Set the active security realms in the order they should be used",
		[]byte(UpdateSecurityRealmsActiveInputSchema),
	)
}

// UpdateSecurityRealmsActiveHandler is the handler function for the UpdateSecurityRealmsActive tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityRealmsActiveHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/realms/active", args, []string{}, contentType, "UpdateSecurityRealmsActive")
}
