// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecurityAnonymous tool
const UpdateSecurityAnonymousInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"enabled\": {\n          \"description\": \"Whether or not Anonymous Access is enabled\",\n          \"type\": \"boolean\"\n        },\n        \"realmName\": {\n          \"description\": \"The name of the authentication realm for the anonymous account\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"userId\": {\n          \"description\": \"The username of the anonymous account\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"realmName\",\n        \"userId\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateSecurityAnonymousMCPTool creates the MCP Tool instance for UpdateSecurityAnonymous
func NewUpdateSecurityAnonymousMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecurityAnonymous",
		"Update Anonymous Access settings",
		[]byte(UpdateSecurityAnonymousInputSchema),
	)
}

// UpdateSecurityAnonymousHandler is the handler function for the UpdateSecurityAnonymous tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecurityAnonymousHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/anonymous", args, []string{}, contentType, "UpdateSecurityAnonymous")
}
