// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateDataStore tool
const UpdateDataStoreInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"advanced\": {\n          \"type\": \"string\"\n        },\n        \"jdbcUrl\": {\n          \"description\": \"The JDBC connection URL for the data store.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"name\": {\n          \"description\": \"The name of the data store.\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"password\": {\n          \"description\": \"The password to use for the JDBC connection.\",\n          \"type\": \"string\"\n        },\n        \"schema\": {\n          \"type\": \"string\"\n        },\n        \"source\": {\n          \"description\": \"The source of the data store.\",\n          \"enum\": [\n            \"local\"\n          ],\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"type\": {\n          \"description\": \"The type of the data store.\",\n          \"enum\": [\n            \"jdbc\"\n          ],\n          \"minLength\": 1,\n          \"type\": \"string\"\n        },\n        \"username\": {\n          \"description\": \"The username to use for the JDBC connection.\",\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"jdbcUrl\",\n        \"name\",\n        \"source\",\n        \"type\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateDataStoreMCPTool creates the MCP Tool instance for UpdateDataStore
func NewUpdateDataStoreMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateDataStore",
		"Update the data store",
		[]byte(UpdateDataStoreInputSchema),
	)
}

// UpdateDataStoreHandler is the handler function for the UpdateDataStore tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateDataStoreHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/beta/data-store", args, []string{}, contentType, "UpdateDataStore")
}
