// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecretsEncryptionReEncrypt tool
const UpdateSecretsEncryptionReEncryptInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"notifyEmail\": {\n          \"description\": \"Optional - Email to notify when task finishes\",\n          \"type\": \"string\"\n        },\n        \"secretKeyId\": {\n          \"description\": \"Key identifier that will be used to re-encrypt secrets\",\n          \"minLength\": 1,\n          \"type\": \"string\"\n        }\n      },\n      \"required\": [\n        \"secretKeyId\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"type\": \"object\"\n}"

// NewUpdateSecretsEncryptionReEncryptMCPTool creates the MCP Tool instance for UpdateSecretsEncryptionReEncrypt
func NewUpdateSecretsEncryptionReEncryptMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecretsEncryptionReEncrypt",
		"Re-encrypt secrets using the specified key - Ensure all nodes have access to the key, and they use the same key",
		[]byte(UpdateSecretsEncryptionReEncryptInputSchema),
	)
}

// UpdateSecretsEncryptionReEncryptHandler is the handler function for the UpdateSecretsEncryptionReEncrypt tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecretsEncryptionReEncryptHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/secrets/encryption/re-encrypt", args, []string{}, contentType, "UpdateSecretsEncryptionReEncrypt")
}
