// Code generated by https://github.com/flowgent-labs/mcpfather

package mcptools

import (
	"context"
	"github.com/mark3labs/mcp-go/mcp"
	"nexus-mcp/pkg/helpers"
)

// Code generated by https://github.com/flowgent-labs/mcpfather

// Input Schema for the UpdateSecuritySsrfProtection tool
const UpdateSecuritySsrfProtectionInputSchema = "{\n  \"properties\": {\n    \"body\": {\n      \"properties\": {\n        \"allowedDomains\": {\n          \"description\": \"List of domain names allowed to bypass SSRF protection\",\n          \"example\": [\n            \"internal.corp.com\",\n            \"registry.local\"\n          ],\n          \"items\": {\n            \"description\": \"List of domain names allowed to bypass SSRF protection\",\n            \"example\": \"[\\\"internal.corp.com\\\",\\\"registry.local\\\"]\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        },\n        \"allowedIPs\": {\n          \"description\": \"List of IP addresses allowed to bypass SSRF protection\",\n          \"example\": [\n            \"10.0.0.50\",\n            \"192.168.1.100\"\n          ],\n          \"items\": {\n            \"description\": \"List of IP addresses allowed to bypass SSRF protection\",\n            \"example\": \"[\\\"10.0.0.50\\\",\\\"192.168.1.100\\\"]\",\n            \"type\": \"string\"\n          },\n          \"type\": \"array\",\n          \"uniqueItems\": true\n        },\n        \"enabled\": {\n          \"description\": \"Whether SSRF protection is enabled\",\n          \"example\": true,\n          \"type\": \"boolean\"\n        }\n      },\n      \"required\": [\n        \"enabled\"\n      ],\n      \"type\": \"object\"\n    }\n  },\n  \"required\": [\n    \"body\"\n  ],\n  \"type\": \"object\"\n}"

// NewUpdateSecuritySsrfProtectionMCPTool creates the MCP Tool instance for UpdateSecuritySsrfProtection
func NewUpdateSecuritySsrfProtectionMCPTool() mcp.Tool {
	return mcp.NewToolWithRawSchema(
		"UpdateSecuritySsrfProtection",
		"Update SSRF protection settings",
		[]byte(UpdateSecuritySsrfProtectionInputSchema),
	)
}

// UpdateSecuritySsrfProtectionHandler is the handler function for the UpdateSecuritySsrfProtection tool.
// It reads tool arguments, forwards the request to the upstream service, and returns the response.
func UpdateSecuritySsrfProtectionHandler(ctx context.Context, request mcp.CallToolRequest) (*mcp.CallToolResult, error) {
	upstream := mcputils.GetUpstreamEndpoint()

	args := request.GetArguments()
	if args == nil {
		args = make(map[string]interface{})
	}
	contentType := "application/json"
	return mcputils.ForwardAndParseResponse(ctx, upstream, "PUT", "/service/rest/v1/security/ssrf-protection", args, []string{}, contentType, "UpdateSecuritySsrfProtection")
}
